---------------------------
-- PRIMARY KEYS CREATION --
---------------------------
ALTER TABLE COLLEAGUE ADD CONSTRAINT COLLEAGUE1 PRIMARY KEY (COLLEAGUE_ID) USING INDEX TABLESPACE tmp00idx;

COMMIT;