---------------------------
-- PRIMARY KEYS CREATION --
---------------------------
ALTER TABLE AUTHENTICATION ADD CONSTRAINT AUTHENTICATIONPK PRIMARY KEY (LOGIN) USING INDEX TABLESPACE tmp00idx;

COMMIT;