---------------------------
-- PRIMARY KEYS CREATION --
---------------------------
ALTER TABLE CATEGORY ADD CONSTRAINT CATEGORYPK PRIMARY KEY (CATEGORY_ID) USING INDEX TABLESPACE tmp00idx;

COMMIT;