---------------------------
-- PRIMARY KEYS CREATION --
---------------------------

ALTER TABLE FREQUENCY ADD CONSTRAINT FREQUENCY_PK PRIMARY KEY (FREQUENCY_ID) USING INDEX TABLESPACE tmp00idx;

COMMIT;