---------------------------
-- PRIMARY KEYS CREATION --
---------------------------

ALTER TABLE MISSION_TOOL ADD CONSTRAINT  MISSION_TOOL_PK PRIMARY KEY (MISSION_ID, TOOL_ID) USING INDEX TABLESPACE tmp00idx;

COMMIT;