---------------------------
-- PRIMARY KEYS CREATION --
---------------------------
ALTER TABLE AUTHENTICATION ADD CONSTRAINT AUTHENTICATIONPK PRIMARY KEY (AUTHENTICATION_ID) USING INDEX TABLESPACE tmp00idx;

COMMIT;