---------------------------
-- PRIMARY KEYS CREATION --
---------------------------
ALTER TABLE BUSINESS_ENGINEER ADD CONSTRAINT BUSINESS_ENGINEERPK PRIMARY KEY (B_ENGINEER_ID) USING INDEX TABLESPACE tmp00idx;

COMMIT;