------------------------
-- CREATION DES INDEX --
------------------------
DROP INDEX COLLEAGUEIDX1;
CREATE INDEX COLLEAGUEIDX1 ON COLLEAGUE (COLLEAGUE_ID) TABLESPACE tmp00idx;

DROP INDEX CATEGORYIDX;
CREATE INDEX CATEGORYIDX ON CATEGORY (CATEGORY_ID) TABLESPACE tmp00idx;

DROP INDEX CONCEPTIDX1;
CREATE INDEX CONCEPTIDX1 ON CONCEPT (CONCEPT_ID) TABLESPACE tmp00idx;

DROP INDEX CONCEPTIDX2;
CREATE INDEX CONCEPTIDX2 ON CONCEPT (CATEGORY_ID) TABLESPACE tmp00idx;

DROP INDEX TOOLIDX1;
CREATE INDEX TOOLIDX1 ON TOOL (TOOL_ID) TABLESPACE tmp00idx;

DROP INDEX TOOLIDX2;
CREATE INDEX TOOLIDX2 ON TOOL (CONCEPT_ID) TABLESPACE tmp00idx;

DROP INDEX OBJECTIVEIDX;
CREATE INDEX OBJECTIVEIDX ON OBJECTIVE (OBJECTIVE_ID) TABLESPACE tmp00idx;

DROP INDEX MISSIONIDX1;
CREATE INDEX MISSIONIDX ON MISSION (MISSION_ID) TABLESPACE tmp00idx;

DROP INDEX MISSIONIDX2;
CREATE INDEX MISSIONIDX2 ON MISSION (COLLEAGUE_ID) TABLESPACE tmp00idx;

DROP INDEX CLIENTIDX1;
CREATE INDEX CLIENTIDX1 ON CLIENT (CLIENT_ID) TABLESPACE tmp00idx;

DROP INDEX FREQUENCYIDX1;
CREATE UNIQUE INDEX FREQUENCYIDX1 ON FREQUENCY (FREQUENCY_ID) TABLESPACE tmp00idx;
