---------------------------
-- FOREIGN KEYS CREATION --
---------------------------

ALTER TABLE AUTHENTICATION ADD CONSTRAINT AUTHENTICATIONFK1 FOREIGN KEY (COLLEAGUE_ID)
	  REFERENCES COLLEAGUE (COLLEAGUE_ID) ON DELETE CASCADE;
 
 ALTER TABLE AUTHENTICATION ADD CONSTRAINT AUTHENTICATIONFK2 FOREIGN KEY (ROLE_ID)
	  REFERENCES USER_ROLE (ROLE_ID);
	 
COMMIT;
