---------------------------
-- FOREIGN KEYS CREATION --
---------------------------
ALTER TABLE EAE_H ADD CONSTRAINT EAE_HFK1 FOREIGN KEY (COLLEAGUE_ID)
	  REFERENCES COLLEAGUE_H (COLLEAGUE_ID) ON DELETE CASCADE ;
 
ALTER TABLE EAE_H ADD CONSTRAINT EAE_HFK2 FOREIGN KEY (MANAGER_ID)
	  REFERENCES COLLEAGUE (COLLEAGUE_ID) ;
 
ALTER TABLE EAE_H ADD CONSTRAINT EAE_HFK3 FOREIGN KEY (PREVIOUS_EAE_ID)
	  REFERENCES EAE_H (EAE_ID) ;

COMMIT;

