---------------------------
-- FOREIGN KEYS CREATION --
---------------------------
ALTER TABLE COLLEAGUE_H ADD CONSTRAINT COLLEAGUE_HFK1 FOREIGN KEY (PROFILE_ID)
	  REFERENCES PROFILE (PROFILE_ID);

COMMIT;