---------------------------
-- FOREIGN KEYS CREATION --
---------------------------
ALTER TABLE COLLEAGUE ADD CONSTRAINT COLLEAGUEFK1 FOREIGN KEY (PROFILE_ID)
	  REFERENCES PROFILE (PROFILE_ID);

COMMIT;