---------------------------
-- FOREIGN KEYS CREATION --
---------------------------
ALTER TABLE OBJECTIVE_TASK ADD CONSTRAINT OBJECTIVETASKFK1 FOREIGN KEY (OBJECTIVE_ID)
	  REFERENCES OBJECTIVE (OBJECTIVE_ID) ;
 
  ALTER TABLE OBJECTIVE_TASK ADD CONSTRAINT OBJECTIVETASKFK2 FOREIGN KEY (TASK_ID)
	  REFERENCES TASK (TASK_ID) ;
	  
COMMIT;
