---------------------------
-- FOREIGN KEYS CREATION --
---------------------------
ALTER TABLE OBJECTIVE ADD CONSTRAINT OBJECTIVEFK1 FOREIGN KEY (COLLEAGUE_ID)
	  REFERENCES COLLEAGUE (COLLEAGUE_ID) ON DELETE CASCADE ;
 
ALTER TABLE OBJECTIVE ADD CONSTRAINT OBJECTIVEFK2 FOREIGN KEY (MANAGER_ID)
	  REFERENCES MANAGER (MANAGER_ID) ;
 
ALTER TABLE OBJECTIVE ADD CONSTRAINT OBJECTIVEFK3 FOREIGN KEY (EAE_ID)
	  REFERENCES EAE (EAE_ID) ;

ALTER TABLE OBJECTIVE ADD CONSTRAINT OBJECTIVEFK4 FOREIGN KEY (COL_OBJ_SCORE_ID)
	  REFERENCES OBJECTIVE_SCORE (OBJECTIVE_SCORE_ID) ;

ALTER TABLE OBJECTIVE ADD CONSTRAINT OBJECTIVEFK5 FOREIGN KEY (MAN_OBJ_SCORE_ID)
	  REFERENCES OBJECTIVE_SCORE (OBJECTIVE_SCORE_ID) ;

COMMIT;