---------------------------
-- FOREIGN KEYS CREATION --
---------------------------
ALTER TABLE MISSION_H ADD CONSTRAINT MISSION_HFK1 FOREIGN KEY (COLLEAGUE_ID)
	  REFERENCES COLLEAGUE_H (COLLEAGUE_ID) ON DELETE CASCADE;
 
  ALTER TABLE MISSION_H ADD CONSTRAINT MISSION_HFK2 FOREIGN KEY (CLIENT_ID)
	  REFERENCES CLIENT (CLIENT_ID) ON DELETE CASCADE;
	  
COMMIT;
