---------------------------
-- FOREIGN KEYS CREATION --
---------------------------
ALTER TABLE CLIENT ADD CONSTRAINT CLIENTFK FOREIGN KEY (SECTEUR_ID)
	  REFERENCES SECTEUR_ACTIVITE (SECTEUR_ID);
COMMIT;
