--------------------
-- TABLE CREATION --
--------------------
DROP TABLE CONCEPT CASCADE CONSTRAINTS;

CREATE TABLE CONCEPT
(
	CONCEPT_ID    VARCHAR2(10) NOT NULL,
	CATEGORY_ID   VARCHAR2(10) NOT NULL,
	CONCEPT_NAME  VARCHAR2(10) NOT NULL
)
TABLESPACE tmp00dta;

COMMENT ON TABLE IS 'Table des concepts';

-----------------------
-- SEQUENCE CREATION --
-----------------------
CREATE SEQUENCE SEQCONCEPT MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 1 NOCACHE;
