--------------------
-- TABLE CREATION --
--------------------
DROP TABLE COLLEAGUE_MANAGER_OBJ CASCADE CONSTRAINTS;

CREATE TABLE COLLEAGUE_MANAGER_OBJ
(
	COLLEAGUE_ID   NUMBER(10,0) NOT NULL,
	MANAGER_ID     NUMBER(10,0) NOT NULL,
	OBJECTIVE_ID   NUMBER(10,0) NOT NULL,
	EA_DATE        DATE NOT NULL,
	EA_DOC         BLOB
)
TABLESPACE tmp00dta;

COMMENT ON TABLE COLLEAGUE_MANAGER_OBJ IS 'Table de relation entre un CM, un collaborateur et un EA';

-----------------------
-- SEQUENCE CREATION --
-----------------------
DROP SEQUENCE SEQCOLLEAGUE_MANAGER_OBJ;

CREATE SEQUENCE SEQCOLLEAGUE_MANAGER_OBJ MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 1 NOCACHE;

COMMIT;
