--------------------
-- TABLE CREATION --
--------------------
DROP TABLE MANAGER CASCADE CONSTRAINTS;

CREATE TABLE MANAGER
(
	MANAGER_ID         NUMBER(2,0)   NOT NULL,
	PROFILE_ID         NUMBER(1,0)   NOT NULL,
	LAST_NAME          VARCHAR2(30)  NOT NULL,
	FIRST_NAME         VARCHAR2(30)  NOT NULL,
	EMAIL              VARCHAR2(50)  NOT NULL,
	PHONE              NUMBER(10),            
	EMPLOYMENT_DATE    DATE          NOT NULL,
	EXPERIENCE         NUMBER(2)     NOT NULL,
	BUSINESS_ENGINEER  VARCHAR2(40)
)
TABLESPACE tmp00dta;

COMMENT ON TABLE MANAGER IS 'Table des Consultants Manager';

-----------------------
-- SEQUENCE CREATION --
-----------------------
DROP SEQUENCE SEQMANAGER;

CREATE SEQUENCE SEQMANAGER MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 1 NOCACHE;

COMMIT;
