--------------------
-- TABLE CREATION --
--------------------
DROP TABLE SKILL CASCADE CONSTRAINTS;

CREATE TABLE SKILL
(
	COLLAB_ID  VARCHAR2(10) NOT NULL,
	TOOL_ID    VARCHAR2(10) NOT NULL,
	SCORE      NUMBER(1)
)
TABLESPACE tmp00dta;

COMMENT ON TABLE SKILL IS 'Table des compétences';

-----------------------
-- SEQUENCE CREATION --
-----------------------
DROP SEQUENCE SEQSKILL;

CREATE SEQUENCE SEQSKILL MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 1 NOCACHE;

COMMIT;
