--------------------
-- TABLE CREATION --
--------------------
DROP TABLE USER_ROLE CASCADE CONSTRAINTS;

CREATE TABLE USER_ROLE
(	
	ROLE_ID  NUMBER(1,0) NOT NULL,
	LABEL   VARCHAR2(50) NOT NULL
)
TABLESPACE tmp00dta;

COMMENT ON TABLE USER_ROLE IS 'Table des rôles';

-----------------------
-- SEQUENCE CREATION --
-----------------------
DROP SEQUENCE SEQROL;

CREATE SEQUENCE SEQROL MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 1 NOCACHE;

COMMIT;