--------------------
-- TABLE CREATION --
--------------------
DROP TABLE OBJECTIVE CASCADE CONSTRAINTS;

CREATE TABLE OBJECTIVE
(
	OBJECTIVE_ID      NUMBER(2) NOT NULL,
	TARGET_DATE       DATE
)
TABLESPACE tmp00dta;

COMMENT ON TABLE OBJECTIVE IS 'Table des objectifs des EA';

-----------------------
-- SEQUENCE CREATION --
-----------------------
DROP SEQUENCE SEQOBJECTIVE;

CREATE SEQUENCE SEQOBJECTIVE MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 1 NOCACHE;

COMMIT;