--------------------
-- TABLE CLIENT --
--------------------
DROP TABLE CLIENT CASCADE CONSTRAINTS;

CREATE TABLE CLIENT
(
	CLIENT_ID     NUMBER(10) NOT NULL,
	CLIENT_NAME   VARCHAR2(30) NOT NULL
)
TABLESPACE tmp00dta;

COMMENT ON TABLE MISSION IS 'Table des clients';

-----------------------
-- SEQUENCE CREATION --
-----------------------
DROP SEQUENCE SEQCLIENT;

CREATE SEQUENCE SEQCLIENT MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 1 NOCACHE;

COMMIT;