--------------------
-- TABLE CREATION --
--------------------
DROP TABLE TOOL CASCADE CONSTRAINTS;

CREATE TABLE TOOL
(
	TOOL_ID         VARCHAR2(10) NOT NULL,
	CONCEPT_ID      VARCHAR2(10) NOT NULL,
	TOOL_NAME       VARCHAR2(20) NOT NULL,
	USE_FREQUENCY   NUMBER(1) NOT NULL,
	LAST_USE        NUMBER(1) NOT NULL
)
TABLESPACE tmp00dta;

COMMENT ON TABLE TOOL IS 'Table des outils';

-----------------------
-- SEQUENCE CREATION --
-----------------------
DROP SEQUENCE SEQTOOL;

CREATE SEQUENCE SEQTOOL MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 1 NOCACHE;

COMMIT;