--------------------
-- TABLE CREATION --
--------------------
DROP TABLE AUTHENTICATION CASCADE CONSTRAINTS;

CREATE TABLE AUTHENTICATION
(	
	AUTHENTICATION_ID  NUMBER(3,0) NOT NULL,
	COLLEAGUE_ID  NUMBER(3,0)    NOT NULL,
	ROLE_ID    NUMBER(1,0)    NOT NULL,
	LOGIN   VARCHAR2(50) UNIQUE NOT NULL,
	PASSWORD   VARCHAR2(20) NOT NULL
)
TABLESPACE tmp00dta;

COMMENT ON TABLE AUTHENTICATION IS 'Table des authentifications';

-----------------------
-- SEQUENCE CREATION --
-----------------------
DROP SEQUENCE SEQAUTH;

CREATE SEQUENCE SEQAUTH MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 1 NOCACHE;

COMMIT;