--------------------
-- TABLE CREATION --
--------------------
DROP TABLE AUTHENTIFICATION CASCADE CONSTRAINTS;

CREATE TABLE AUTHENTIFICATION
(	
	AUTHENTIFICATION_ID  NUMBER(3,0) NOT NULL,
	COLLAB_ID  NUMBER(3,0)    NOT NULL,
	LOGIN   VARCHAR2(50) UNIQUE NOT NULL,
	PASSWORD   VARCHAR2(20) NOT NULL
)
TABLESPACE tmp00dta;

COMMENT ON TABLE AUTHENTIFICATION IS 'Table des Authentification';

-----------------------
-- SEQUENCE CREATION --
-----------------------
DROP SEQUENCE SEQAUTH;

CREATE SEQUENCE SEQAUTH MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 1 NOCACHE;

COMMIT;