--------------------
-- TABLE CREATION --
--------------------
DROP TABLE MANAGER CASCADE CONSTRAINTS;

CREATE TABLE MANAGER
(
	MANAGER_ID         VARCHAR2(10) NOT NULL,
	PROFILE_ID         VARCHAR2(10) NOT NULL,
	LAST_NAME          VARCHAR2(20) NOT NULL,
	FIRST_NAME         VARCHAR2(20) NOT NULL,
	EMAIL              VARCHAR2(50),
	PHONE              NUMBER(10),
	EMPLOYMENT_DATE    DATE,
	BUSINESS_ENGINEER  VARCHAR2(40)
)
TABLESPACE tmp00dta;

COMMENT ON TABLE MANAGER IS 'Table deS Consultants Manager';

-----------------------
-- SEQUENCE CREATION --
-----------------------
DROP SEQUENCE SEQMANAGER;

CREATE SEQUENCE SEQMANAGER MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 1 NOCACHE;

COMMIT;
