--------------------
-- TABLE CREATION --
--------------------
DROP TABLE BUSINESS_ENGINEER CASCADE CONSTRAINTS;

CREATE TABLE BUSINESS_ENGINEER
(
	B_ENGINEER_ID    	NUMBER(10,0)  NOT NULL,
	FIRST_NAME          VARCHAR2(40) NOT NULL,
	LAST_NAME   		VARCHAR2(40) NOT NULL,
	BUSINESS_UNIT       VARCHAR2(40) NOT NULL
)
TABLESPACE tmp00dta;

COMMENT ON TABLE BUSINESS_ENGINEER IS 'Table des Ingénieurs d Affaire';

-----------------------
-- SEQUENCE CREATION --
-----------------------
DROP SEQUENCE SEQBUSINESS_ENGINEER;

CREATE SEQUENCE SEQBUSINESS_ENGINEER MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 1 NOCACHE;

COMMIT;