--------------------
-- TABLE CREATION --
--------------------
DROP TABLE COLLABORATOR CASCADE CONSTRAINTS;

CREATE TABLE COLLABORATOR
(
	COLLAB_ID    	NUMBER(2)    NOT NULL,
	MANAGER_ID   	NUMBER(2)    NOT NULL,
	PROFILE_ID    	NUMBER(2)    NOT NULL,
	LAST_NAME    	VARCHAR2(20)    NOT NULL,
	FIRST_NAME   	VARCHAR2(20)    NOT NULL,
	EMAIL        	VARCHAR2(50)    NOT NULL,
	PHONE        	NUMBER(10),
	EMPLOYMENT_DATE DATE            NOT NULL,
	EXPERIENCE      NUMBER(2)       NOT NULL,
	BUSINESS_ENGINEER VARCHAR2(40)
)
TABLESPACE tmp00dta;

COMMENT ON TABLE COLLABORATOR IS 'Table des collaborateurs';

-----------------------
-- SEQUENCE CREATION --
-----------------------
DROP SEQUENCE SEQCOLLABORATOR;

CREATE SEQUENCE SEQCOLLABORATOR MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 1 NOCACHE;

COMMIT;
