--------------------
-- TABLE CREATION --
--------------------
DROP TABLE CATEGORY CASCADE CONSTRAINTS;

CREATE TABLE CATEGORY
(
	CATEGORY_ID     VARCHAR2(10) NOT NULL,
	CATEGORY_NAME   VARCHAR2(20) NOT NULL
)
TABLESPACE tmp00dta;

COMMENT ON TABLE IS 'Table deS Catégories';

-----------------------
-- SEQUENCE CREATION --
-----------------------
CREATE SEQUENCE SEQCATEGORY MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 1 NOCACHE;
