/**This script delete all data*/

-- DISABLE FK CONSTRAINTS

SET FOREIGN_KEY_CHECKS = 0;


----TRUNCATE
TRUNCATE TABLE OBJECTIVE_TASK;
TRUNCATE TABLE TASK;
TRUNCATE TABLE COLLEAGUE_MANAGER_OBJ;
TRUNCATE TABLE OBJECTIVE;
TRUNCATE TABLE MISSION ;
TRUNCATE TABLE SKILL ;
TRUNCATE TABLE COLLEAGUE;
TRUNCATE TABLE PROFILE ;
TRUNCATE TABLE TOOL ;
TRUNCATE TABLE CONCEPT;
TRUNCATE TABLE CATEGORY ;
TRUNCATE TABLE AUTHENTICATION;
TRUNCATE TABLE BUSINESS_ENGINEER;
TRUNCATE TABLE CLIENT ;
TRUNCATE TABLE MISSION_TOOL;
TRUNCATE TABLE MANAGER;
TRUNCATE TABLE PARAMETER;
TRUNCATE TABLE USER_ROLE;
COMMIT;


--- Reactivate CONSTRAINT

SET FOREIGN_KEY_CHECKS = 0;