--------------------
-- TABLE CREATION --
--------------------
DROP TABLE IF EXISTS TOPIC CASCADE;

CREATE TABLE TOPIC 
   (	TOPIC_ID 		INT NOT NULL PRIMARY KEY, 
   		TOPIC_LABEL 	VARCHAR(60) NOT NULL
   );
-- TABLESPACE tmp00dta;

-- COMMENT ON TABLE TOPIC IS '';

