--------------------
-- TABLE CREATION --
--------------------
DROP TABLE IF EXISTS SKILL CASCADE;

 CREATE TABLE SKILL 
   (	COLLEAGUE_ID INT NOT NULL, 
	TOOL_ID INT NOT NULL, 
	USE_FREQUENCY INT NOT NULL, 
	NO_USING_TIME INT NOT NULL, 
	SCORE INT NOT NULL
   );
-- TABLESPACE tmp00dta;

-- COMMENT ON TABLE SKILL IS 'Table des compétences';


