--------------------
-- TABLE CREATION --
--------------------
DROP TABLE IF EXISTS TOOL CASCADE;

CREATE TABLE TOOL 
   (	TOOL_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
	CONCEPT_ID INT NOT NULL, 
	TOOL_NAME VARCHAR(30) NOT NULL
   );
-- TABLESPACE tmp00dta;

-- COMMENT ON TABLE TOOL IS 'Table des outils';

