--------------------
-- TABLE CREATION --
--------------------
DROP TABLE IF EXISTS OBJECTIVE CASCADE;

CREATE TABLE OBJECTIVE 
   (	OBJECTIVE_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
	TARGET_DATE DATE
   );
-- TABLESPACE tmp00dta;

-- COMMENT ON TABLE OBJECTIVE IS 'Table des objectifs des EA';

