--------------------
-- TABLE CREATION --
--------------------

DROP TABLE IF EXISTS PARAMETER CASCADE;

CREATE TABLE PARAMETER 
   (	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
	NAME VARCHAR(1) NOT NULL, 
	VALUE INT NOT NULL, 
	CODE_LANG VARCHAR(5) NOT NULL, 
	CRITERIA_ID INT NOT NULL
   );