--------------------
-- TABLE CREATION --
--------------------
DROP TABLE IF EXISTS USER_ROLE CASCADE;

CREATE TABLE USER_ROLE 
   (	ROLE_ID INT AUTO_INCREMENT PRIMARY KEY, 
	LABEL VARCHAR(50)
   );
-- TABLESPACE tmp00dta;

-- COMMENT ON TABLE USER_ROLE IS 'Table des rôles';
