--------------------
-- TABLE CREATION --
--------------------
DROP TABLE IF EXISTS MISSION_H CASCADE ;

CREATE TABLE MISSION_H
   (	MISSION_ID INT NOT NULL PRIMARY KEY, 
	COLLEAGUE_ID INT NOT NULL, 
	TITLE VARCHAR(60), 
	PLACE VARCHAR(60) NOT NULL, 
	CLIENT_ID INT NOT NULL, 
	NOTES LONGTEXT, 
	START_DATE DATE NOT NULL, 
	END_DATE DATE
   );
-- TABLESPACE tmp00dta;

-- COMMENT ON TABLE MISSION_H IS 'Table Historique des missions';

