--------------------
-- TABLE CREATION --
--------------------
DROP TABLE IF EXISTS COLLEAGUE_H CASCADE ;

CREATE TABLE COLLEAGUE_H 
   (	COLLEAGUE_ID INT NOT NULL PRIMARY KEY, 
	MANAGER_ID INT, 
	PROFILE_ID INT NOT NULL, 
	LAST_NAME VARCHAR(30) NOT NULL, 
	FIRST_NAME VARCHAR(30) NOT NULL, 
	EMAIL VARCHAR(50) NOT NULL, 
	PHONE VARCHAR(10), 
	EMPLOYMENT_DATE DATE NOT NULL, 
	EXPERIENCE INT NOT NULL, 
	B_ENGINEER_ID INT,
	TITLE VARCHAR(5) NOT NULL
   );
-- TABLESPACE tmp00dta;

-- COMMENT ON TABLE COLLEAGUE_H IS 'Table Historique des collaborateurs';


