--------------------
-- TABLE CREATION --
--------------------
DROP TABLE IF EXISTS BUSINESS_ENGINEER CASCADE;

CREATE TABLE BUSINESS_ENGINEER
   (	B_ENGINEER_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
	FIRST_NAME VARCHAR(40) NOT NULL, 
	LAST_NAME VARCHAR(40) NOT NULL, 
	BUSINESS_UNIT VARCHAR(40) NOT NULL
   );
-- TABLESPACE tmp00dta;

-- COMMENT ON TABLE BUSINESS_ENGINEER IS 'Table des Ingénieurs d Affaire';


