--------------------
-- TABLE CREATION --
--------------------
DROP TABLE IF EXISTS AUTHENTICATION CASCADE ;

 CREATE TABLE AUTHENTICATION 
   (AUTHENTICATION_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
	COLLEAGUE_ID INT NOT NULL, 
	ROLE_ID INT NOT NULL, 
	LOGIN VARCHAR(50) NOT NULL, 
	PASSWORD VARCHAR(50) NOT NULL
   );
-- TABLESPACE tmp00dta;

-- COMMENT ON TABLE AUTHENTICATION IS 'Table des authentifications';
