--------------------
-- TABLE CREATION --
--------------------
DROP TABLE IF EXISTS OBJECTIVE_H CASCADE;

CREATE TABLE OBJECTIVE_H
   (	OBJECTIVE_ID 			INT NOT NULL PRIMARY KEY, 
   		COLLEAGUE_ID 			INT NOT NULL,
   		MANAGER_ID 				INT NOT NULL,
   		EAE_ID 					INT NOT NULL,
   		TITLE 					VARCHAR(60) NOT NULL,
   		GOAL 					VARCHAR(200) NOT NULL,
		TARGET_DATE 			DATE,
		INDICATORS 				TEXT,
		MEANS 					TEXT,
		COL_OBJ_SCORE_ID		TINYINT UNSIGNED,
		MAN_OBJ_SCORE_ID 		TINYINT UNSIGNED,
		MOTIVES_OR_RESTRAINTS 	TEXT,
		COMMENTS 				TEXT
   );
-- TABLESPACE tmp00dta;

-- COMMENT ON TABLE OBJECTIVE_H IS 'Table Historique des objectifs des EA';

