--------------------
-- TABLE CREATION --
--------------------
DROP TABLE IF EXISTS EAE CASCADE;

CREATE TABLE EAE 
   (	EAE_ID 					INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
   		COLLEAGUE_ID 			INT NOT NULL,
   		MANAGER_ID 				INT NOT NULL,
   		EAE_DATE 				DATE NOT NULL,
   		PROFILE_LABEL 			VARCHAR(60),
   		PREVIOUS_EAE_ID 		INT NOT NULL,
		COLLEAGUES_STRENGTHS 	LONGTEXT,
		COLLEAGUES_WEAKNESSES 	LONGTEXT,
		EAE_STATE_ID			TINYINT UNSIGNED,
		COLLEAGUES_SYNTHESIS 	LONGTEXT,
		MANAGERS_SYNTHESIS 		LONGTEXT,
		OTHER 					LONGTEXT
		
   );
-- TABLESPACE tmp00dta;

-- COMMENT ON TABLE EAE IS 'Table des EAE';

