--------------------
-- TABLE CLIENT --
--------------------
DROP TABLE IF EXISTS CLIENT CASCADE;

 CREATE TABLE CLIENT 
   (	CLIENT_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
	CLIENT_NAME VARCHAR(70) NOT NULL
   );
-- TABLESPACE tmp00dta;

-- COMMENT ON TABLE MISSION IS 'Table des clients';

