--------------------
-- TABLE CREATION --
--------------------
DROP TABLE IF EXISTS OBJECTIVE_SCORE CASCADE;

CREATE TABLE OBJECTIVE_SCORE 
   (	OBJECTIVE_SCORE_ID 		TINYINT UNSIGNED NOT NULL PRIMARY KEY, 
   		OBJECTIVE_SCORE_LABEL 	VARCHAR(60) NOT NULL
   );
-- TABLESPACE tmp00dta;

-- COMMENT ON TABLE OBJECTIVE_SCORE IS 'Table des scores obtenus aux objectifs des EA';

