--------------------
-- TABLE CREATION --
--------------------
DROP TABLE IF EXISTS CATEGORY CASCADE ;

CREATE TABLE CATEGORY 
   (	CATEGORY_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
	CATEGORY_NAME VARCHAR(20) NOT NULL
   );
-- TABLESPACE tmp00dta;

-- COMMENT ON TABLE CATEGORY IS 'Table des Catégories';

