--------------------
-- TABLE CREATION --
--------------------
DROP TABLE IF EXISTS COLLEAGUE_MANAGER_OBJ CASCADE ;

CREATE TABLE COLLEAGUE_MANAGER_OBJ 
   (	COLLEAGUE_ID INT NOT NULL, 
	MANAGER_ID INT NOT NULL, 
	OBJECTIVE_ID INT NOT NULL, 
	EA_DATE DATE NOT NULL, 
	EA_DOC BLOB
   );
-- TABLESPACE tmp00dta;

-- COMMENT ON TABLE COLLEAGUE_MANAGER_OBJ IS 'Table de relation entre un CM, un collaborateur et un EA';

