--------------------
-- TABLE CREATION --
--------------------
ALTER TABLE EAE_H DROP FOREIGN KEY EAE_HFK1 ;
ALTER TABLE EAE_H DROP FOREIGN KEY EAE_HFK2 ;
ALTER TABLE EAE_H DROP FOREIGN KEY EAE_HFK3 ;
ALTER TABLE EAE_H DROP FOREIGN KEY EAE_HFK4 ;

ALTER TABLE OBJECTIVE_H DROP FOREIGN KEY OBJECTIVE_HFK3 ;

DROP TABLE IF EXISTS EAE_H CASCADE;

CREATE TABLE EAE_H
   (	EAE_ID 					INT NOT NULL PRIMARY KEY, 
   		COLLEAGUE_ID 			INT NOT NULL,
   		MANAGER_ID 				INT NOT NULL,
   		EAE_DATE 				DATE NOT NULL,
   		PROFILE_LABEL 			VARCHAR(60),
   		PREVIOUS_EAE_ID 		INT,
		YEAR_SYNTHESIS 			TEXT,
		COLLEAGUES_STRENGTHS 	TEXT,
		COLLEAGUES_WEAKNESSES 	TEXT,
		MEANS_TO_PROGRESS	 	TEXT,
		EAE_STATE_ID			TINYINT UNSIGNED NOT NULL,
		COLLEAGUES_SYNTHESIS 	TEXT,
		MANAGERS_SYNTHESIS 		TEXT,
		OTHER 					TEXT,
		SALARY 					INTEGER UNSIGNED
   );
   
   
ALTER TABLE OBJECTIVE_H ADD CONSTRAINT OBJECTIVE_HFK3 FOREIGN KEY (EAE_ID)
	  REFERENCES EAE_H (EAE_ID) ;

-- TABLESPACE tmp00dta;

-- COMMENT ON TABLE EAE_H IS 'Table Historique des EAE';

