--------------------
-- TABLE CREATION --
--------------------
DROP TABLE IF EXISTS CONCEPT CASCADE ;

 CREATE TABLE CONCEPT 
   (	CONCEPT_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
	CATEGORY_ID INT NOT NULL, 
	CONCEPT_NAME VARCHAR(20) NOT NULL
   );
-- TABLESPACE tmp00dta;

-- COMMENT ON TABLE CONCEPT IS 'Table des concepts';

