--------------------
-- TABLE CREATION --
--------------------

DROP TABLE IF EXISTS MANAGER CASCADE ;

  CREATE TABLE MANAGER 
   (	MANAGER_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
	PROFILE_ID INT NOT NULL, 
	LAST_NAME VARCHAR(30) NOT NULL, 
	FIRST_NAME VARCHAR(30) NOT NULL, 
	EMAIL VARCHAR(50) NOT NULL, 
	PHONE INT, 
	EMPLOYMENT_DATE DATE NOT NULL, 
	EXPERIENCE INT NOT NULL, 
	BUSINESS_ENGINEER VARCHAR(40)
   );