--------------------------------------------
-- TABLE DE RELATION OBJECTIFS ET ACTIONS --
--------------------------------------------

---------------------------
-- FOREIGN KEYS CREATION --
---------------------------
ALTER TABLE OBJACTIONS ADD CONSTRAINT OBJACTIONSFK1 FOREIGN KEY (OBJ_EA_ID) REFERENCES EAOBJECTIVE (OBJ_EA_ID);
ALTER TABLE OBJACTIONS ADD CONSTRAINT OBJACTIONSFK2 FOREIGN KEY (ACTION_ID) REFERENCES ACTIONS (ACTION_ID);

