package com.novedia.talentmap.web.ecrans;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.TabSheet;

/**
 * The accueil custom component
 * 
 * @author e.moumbe
 * 
 */
public class Accueil extends CustomComponent {

    /**
     * UID
     */
    private static final long serialVersionUID = 1L;

    @AutoGenerated
    private AbsoluteLayout mainLayout;

    @AutoGenerated
    private TabSheet tabSheet_2;

    @AutoGenerated
    private Label label_5;

    @AutoGenerated
    private Label label_4;

    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

    /**
     * The constructor should first build the main layout, set the composition
     * root and then do any custom initialization.
     * 
     * The constructor will not be automatically regenerated by the visual
     * editor.
     */
    public Accueil() {
	buildMainLayout();
	setCompositionRoot(mainLayout);

	// TODO add user code here
    }

    @AutoGenerated
    private AbsoluteLayout buildMainLayout() {
	// common part: create layout
	mainLayout = new AbsoluteLayout();
	mainLayout.setImmediate(false);
	mainLayout.setWidth("100%");
	mainLayout.setHeight("100%");
	mainLayout.setMargin(false);

	// top-level component properties
	setWidth("100.0%");
	setHeight("100.0%");

	// tabSheet_2
	tabSheet_2 = buildTabSheet_2();
	mainLayout.addComponent(tabSheet_2, "top:120.0px;left:81.0px;");

	return mainLayout;
    }

    @AutoGenerated
    private TabSheet buildTabSheet_2() {
	// common part: create layout
	tabSheet_2 = new TabSheet();
	tabSheet_2.setImmediate(true);
	tabSheet_2.setWidth("680px");
	tabSheet_2.setHeight("460px");

	// label_4
	label_4 = new Label();
	label_4.setImmediate(false);
	label_4.setWidth("-1px");
	label_4.setHeight("18px");
	label_4.setValue("Page recherche (page par défaut)");
	tabSheet_2.addTab(label_4, "Recherche", null);

	// label_5
	label_5 = new Label();
	label_5.setImmediate(false);
	label_5.setWidth("-1px");
	label_5.setHeight("-1px");
	label_5.setValue("Page profil");
	tabSheet_2.addTab(label_5, "Fiche Profil", null);

	return tabSheet_2;
    }

}
