package com.novedia.talentmap.web.ecrans;


import com.vaadin.annotations.AutoGenerated;
import com.vaadin.terminal.ExternalResource;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Embedded;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.NativeSelect;
import com.vaadin.ui.Panel;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

public class fiche_profil_creation extends CustomComponent {

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Panel panel_1;
	@AutoGenerated
	private VerticalLayout verticalLayout_1;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_8;
	@AutoGenerated
	private Button valid_note;
	@AutoGenerated
	private Button annul_note;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_7;
	@AutoGenerated
	private Embedded embedded_12;
	@AutoGenerated
	private Embedded embedded_14;
	@AutoGenerated
	private Embedded embedded_15;
	@AutoGenerated
	private Embedded embedded_13;
	@AutoGenerated
	private Embedded embedded_16;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_6;
	@AutoGenerated
	private Embedded embedded_9;
	@AutoGenerated
	private Embedded embedded_10;
	@AutoGenerated
	private Embedded embedded_11;
	@AutoGenerated
	private Embedded embedded_8;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_5;
	@AutoGenerated
	private Embedded embedded_6;
	@AutoGenerated
	private Embedded embedded_7;
	@AutoGenerated
	private Embedded embedded_5;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_4;
	@AutoGenerated
	private Embedded embedded_4;
	@AutoGenerated
	private Embedded embedded_3;
	@AutoGenerated
	private Embedded embedded_1;
	@AutoGenerated
	private Panel panel_5;
	@AutoGenerated
	private VerticalLayout verticalLayout_5;
	@AutoGenerated
	private Button btn_ok;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_3;
	@AutoGenerated
	private Label outil;
	@AutoGenerated
	private NativeSelect outil_list;
	@AutoGenerated
	private NativeSelect concept_list;
	@AutoGenerated
	private Label concept;
	@AutoGenerated
	private NativeSelect categorie_list;
	@AutoGenerated
	private Label categorie;
	@AutoGenerated
	private Panel panel_3;
	@AutoGenerated
	private VerticalLayout verticalLayout_2;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_2;
	@AutoGenerated
	private Button btn_annuler;
	@AutoGenerated
	private Button btn_enregistrer;
	@AutoGenerated
	private Panel panel_2;
	@AutoGenerated
	private VerticalLayout verticalLayout_3;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_1;
	@AutoGenerated
	private Button btn_non;
	@AutoGenerated
	private Button btn_oui;
	@AutoGenerated
	private Label question_competence;
	@AutoGenerated
	private GridLayout gridLayout_2;
	@AutoGenerated
	private TextField textField_1;
	@AutoGenerated
	private Label ing_affaire;
	@AutoGenerated
	private Label consul_manager_value;
	@AutoGenerated
	private Label consul_manager;
	@AutoGenerated
	private Label sortie_value;
	@AutoGenerated
	private Label sortie;
	@AutoGenerated
	private Label duree_mission_value;
	@AutoGenerated
	private Label duree_mission;
	@AutoGenerated
	private NativeSelect client_list;
	@AutoGenerated
	private Label client;
	@AutoGenerated
	private Label annee_exp_value;
	@AutoGenerated
	private Label annee_exp;
	@AutoGenerated
	private Label label_13;
	@AutoGenerated
	private Label novedia_entree_value;
	@AutoGenerated
	private Label novedia_entree;
	@AutoGenerated
	private NativeSelect profil_value;
	@AutoGenerated
	private Label profil;
	@AutoGenerated
	private Label label_14;
	@AutoGenerated
	private Label email_value;
	@AutoGenerated
	private Label email;
	@AutoGenerated
	private Label num_tel;
	@AutoGenerated
	private Label tel;
	@AutoGenerated
	private Button upload_cv;
	@AutoGenerated
	private Label julien;
	@AutoGenerated
	private Label prenom;
	@AutoGenerated
	private Label Collet;
	@AutoGenerated
	private Label nom;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public fiche_profil_creation() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// panel_3
		panel_3 = buildPanel_3();
		mainLayout.addComponent(panel_3, "top:0.0px;left:0.0px;");
		
		// panel_5
		panel_5 = buildPanel_5();
		mainLayout.addComponent(panel_5, "top:540.0px;left:-45.0px;");
		
		// panel_1
		panel_1 = buildPanel_1();
		mainLayout.addComponent(panel_1, "top:540.0px;left:680.0px;");
		
		return mainLayout;
	}

	@AutoGenerated
	private Panel buildPanel_3() {
		// common part: create layout
		panel_3 = new Panel();
		panel_3.setImmediate(false);
		panel_3.setWidth("730px");
		panel_3.setHeight("520px");
		
		// verticalLayout_2
		verticalLayout_2 = buildVerticalLayout_2();
		panel_3.setContent(verticalLayout_2);
		
		return panel_3;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_2() {
		// common part: create layout
		verticalLayout_2 = new VerticalLayout();
		verticalLayout_2.setImmediate(false);
		verticalLayout_2.setWidth("100.02%");
		verticalLayout_2.setHeight("100.0%");
		verticalLayout_2.setMargin(false);
		
		// gridLayout_2
		gridLayout_2 = buildGridLayout_2();
		verticalLayout_2.addComponent(gridLayout_2);
		
		// panel_2
		panel_2 = buildPanel_2();
		verticalLayout_2.addComponent(panel_2);
		
		// horizontalLayout_2
		horizontalLayout_2 = buildHorizontalLayout_2();
		verticalLayout_2.addComponent(horizontalLayout_2);
		verticalLayout_2.setComponentAlignment(horizontalLayout_2,
				new Alignment(48));
		
		return verticalLayout_2;
	}

	@AutoGenerated
	private GridLayout buildGridLayout_2() {
		// common part: create layout
		gridLayout_2 = new GridLayout();
		gridLayout_2.setImmediate(false);
		gridLayout_2.setWidth("726px");
		gridLayout_2.setHeight("239px");
		gridLayout_2.setMargin(true);
		gridLayout_2.setColumns(12);
		gridLayout_2.setRows(5);
		
		// nom
		nom = new Label();
		nom.setImmediate(false);
		nom.setWidth("-1px");
		nom.setHeight("-1px");
		nom.setValue("Nom : ");
		gridLayout_2.addComponent(nom, 0, 0);
		gridLayout_2.setComponentAlignment(nom, new Alignment(33));
		
		// Collet
		Collet = new Label();
		Collet.setImmediate(false);
		Collet.setWidth("-1px");
		Collet.setHeight("-1px");
		Collet.setValue("Collet");
		gridLayout_2.addComponent(Collet, 1, 0);
		gridLayout_2.setComponentAlignment(Collet, new Alignment(33));
		
		// prenom
		prenom = new Label();
		prenom.setImmediate(false);
		prenom.setWidth("-1px");
		prenom.setHeight("-1px");
		prenom.setValue("Prénom :");
		gridLayout_2.addComponent(prenom, 3, 0);
		gridLayout_2.setComponentAlignment(prenom, new Alignment(33));
		
		// julien
		julien = new Label();
		julien.setImmediate(false);
		julien.setWidth("-1px");
		julien.setHeight("-1px");
		julien.setValue("Julien");
		gridLayout_2.addComponent(julien, 4, 0);
		gridLayout_2.setComponentAlignment(julien, new Alignment(33));
		
		// upload_cv
		upload_cv = new Button();
		upload_cv.setCaption("Upload CV (image)");
		upload_cv.setImmediate(true);
		upload_cv.setWidth("-1px");
		upload_cv.setHeight("-1px");
		gridLayout_2.addComponent(upload_cv, 9, 0);
		gridLayout_2.setComponentAlignment(upload_cv, new Alignment(33));
		
		// tel
		tel = new Label();
		tel.setImmediate(false);
		tel.setWidth("-1px");
		tel.setHeight("-1px");
		tel.setValue("Tél :");
		gridLayout_2.addComponent(tel, 0, 1);
		gridLayout_2.setComponentAlignment(tel, new Alignment(33));
		
		// num_tel
		num_tel = new Label();
		num_tel.setImmediate(false);
		num_tel.setWidth("-1px");
		num_tel.setHeight("-1px");
		num_tel.setValue("0000000000");
		gridLayout_2.addComponent(num_tel, 1, 1);
		gridLayout_2.setComponentAlignment(num_tel, new Alignment(33));
		
		// email
		email = new Label();
		email.setImmediate(false);
		email.setWidth("-1px");
		email.setHeight("-1px");
		email.setValue("E-mail :");
		gridLayout_2.addComponent(email, 3, 1);
		gridLayout_2.setComponentAlignment(email, new Alignment(33));
		
		// email_value
		email_value = new Label();
		email_value.setImmediate(false);
		email_value.setWidth("-1px");
		email_value.setHeight("-1px");
		email_value.setValue("nieluj974@gmail.com");
		gridLayout_2.addComponent(email_value, 4, 1);
		gridLayout_2.setComponentAlignment(email_value, new Alignment(33));
		
		// label_14
		label_14 = new Label();
		label_14.setImmediate(false);
		label_14.setWidth("-1px");
		label_14.setHeight("-1px");
		label_14.setValue("   ");
		gridLayout_2.addComponent(label_14, 7, 1);
		
		// profil
		profil = new Label();
		profil.setImmediate(false);
		profil.setWidth("-1px");
		profil.setHeight("-1px");
		profil.setValue("Profil :");
		gridLayout_2.addComponent(profil, 8, 1);
		gridLayout_2.setComponentAlignment(profil, new Alignment(33));
		
		// profil_value
		profil_value = new NativeSelect();
		profil_value.setImmediate(false);
		profil_value.setWidth("138px");
		profil_value.setHeight("20px");
		gridLayout_2.addComponent(profil_value, 9, 1);
		gridLayout_2.setComponentAlignment(profil_value, new Alignment(33));
		
		// novedia_entree
		novedia_entree = new Label();
		novedia_entree.setImmediate(false);
		novedia_entree.setWidth("-1px");
		novedia_entree.setHeight("-1px");
		novedia_entree.setValue("Date d'entrée Novedia :");
		gridLayout_2.addComponent(novedia_entree, 0, 2);
		gridLayout_2.setComponentAlignment(novedia_entree, new Alignment(33));
		
		// novedia_entree_value
		novedia_entree_value = new Label();
		novedia_entree_value.setImmediate(false);
		novedia_entree_value.setWidth("-1px");
		novedia_entree_value.setHeight("-1px");
		novedia_entree_value.setValue("13/04/2012");
		gridLayout_2.addComponent(novedia_entree_value, 1, 2);
		gridLayout_2.setComponentAlignment(novedia_entree_value, new Alignment(
				33));
		
		// label_13
		label_13 = new Label();
		label_13.setImmediate(false);
		label_13.setWidth("-1px");
		label_13.setHeight("-1px");
		label_13.setValue("       ");
		gridLayout_2.addComponent(label_13, 2, 2);
		
		// annee_exp
		annee_exp = new Label();
		annee_exp.setImmediate(false);
		annee_exp.setWidth("-1px");
		annee_exp.setHeight("-1px");
		annee_exp.setValue("Années d'expérience :    ");
		gridLayout_2.addComponent(annee_exp, 3, 2);
		gridLayout_2.setComponentAlignment(annee_exp, new Alignment(33));
		
		// annee_exp_value
		annee_exp_value = new Label();
		annee_exp_value.setImmediate(false);
		annee_exp_value.setWidth("-1px");
		annee_exp_value.setHeight("-1px");
		annee_exp_value.setValue("5 ans");
		gridLayout_2.addComponent(annee_exp_value, 4, 2);
		gridLayout_2.setComponentAlignment(annee_exp_value, new Alignment(33));
		
		// client
		client = new Label();
		client.setImmediate(false);
		client.setWidth("-1px");
		client.setHeight("-1px");
		client.setValue("Client : ");
		gridLayout_2.addComponent(client, 0, 3);
		gridLayout_2.setComponentAlignment(client, new Alignment(33));
		
		// client_list
		client_list = new NativeSelect();
		client_list.setImmediate(false);
		client_list.setWidth("62px");
		client_list.setHeight("-1px");
		gridLayout_2.addComponent(client_list, 1, 3);
		gridLayout_2.setComponentAlignment(client_list, new Alignment(33));
		
		// duree_mission
		duree_mission = new Label();
		duree_mission.setImmediate(false);
		duree_mission.setWidth("-1px");
		duree_mission.setHeight("-1px");
		duree_mission.setValue("Durée mission : ");
		gridLayout_2.addComponent(duree_mission, 3, 3);
		gridLayout_2.setComponentAlignment(duree_mission, new Alignment(33));
		
		// duree_mission_value
		duree_mission_value = new Label();
		duree_mission_value.setImmediate(false);
		duree_mission_value.setWidth("-1px");
		duree_mission_value.setHeight("-1px");
		duree_mission_value.setValue("1 an");
		gridLayout_2.addComponent(duree_mission_value, 4, 3);
		gridLayout_2.setComponentAlignment(duree_mission_value, new Alignment(
				33));
		
		// sortie
		sortie = new Label();
		sortie.setImmediate(false);
		sortie.setWidth("-1px");
		sortie.setHeight("-1px");
		sortie.setValue("Sortie : ");
		gridLayout_2.addComponent(sortie, 8, 3);
		gridLayout_2.setComponentAlignment(sortie, new Alignment(33));
		
		// sortie_value
		sortie_value = new Label();
		sortie_value.setImmediate(false);
		sortie_value.setWidth("-1px");
		sortie_value.setHeight("-1px");
		sortie_value.setValue("13/04/2012");
		gridLayout_2.addComponent(sortie_value, 9, 3);
		gridLayout_2.setComponentAlignment(sortie_value, new Alignment(33));
		
		// consul_manager
		consul_manager = new Label();
		consul_manager.setImmediate(false);
		consul_manager.setWidth("-1px");
		consul_manager.setHeight("-1px");
		consul_manager.setValue("Consultant mangager : ");
		gridLayout_2.addComponent(consul_manager, 0, 4);
		gridLayout_2.setComponentAlignment(consul_manager, new Alignment(33));
		
		// consul_manager_value
		consul_manager_value = new Label();
		consul_manager_value.setImmediate(false);
		consul_manager_value.setWidth("-1px");
		consul_manager_value.setHeight("-1px");
		consul_manager_value.setValue("Jean-Max");
		gridLayout_2.addComponent(consul_manager_value, 1, 4);
		gridLayout_2.setComponentAlignment(consul_manager_value, new Alignment(
				33));
		
		// ing_affaire
		ing_affaire = new Label();
		ing_affaire.setImmediate(false);
		ing_affaire.setWidth("-1px");
		ing_affaire.setHeight("-1px");
		ing_affaire.setValue("Ingénieur d'affaire : ");
		gridLayout_2.addComponent(ing_affaire, 3, 4);
		gridLayout_2.setComponentAlignment(ing_affaire, new Alignment(33));
		
		// textField_1
		textField_1 = new TextField();
		textField_1.setImmediate(false);
		textField_1.setWidth("-1px");
		textField_1.setHeight("24px");
		textField_1.setReadThrough(false);
		textField_1.setSecret(false);
		gridLayout_2.addComponent(textField_1, 4, 4);
		gridLayout_2.setComponentAlignment(textField_1, new Alignment(33));
		
		return gridLayout_2;
	}

	@AutoGenerated
	private Panel buildPanel_2() {
		// common part: create layout
		panel_2 = new Panel();
		panel_2.setImmediate(false);
		panel_2.setWidth("726px");
		panel_2.setHeight("164px");
		
		// verticalLayout_3
		verticalLayout_3 = buildVerticalLayout_3();
		panel_2.setContent(verticalLayout_3);
		
		return panel_2;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_3() {
		// common part: create layout
		verticalLayout_3 = new VerticalLayout();
		verticalLayout_3.setImmediate(false);
		verticalLayout_3.setWidth("100.42%");
		verticalLayout_3.setHeight("101.7%");
		verticalLayout_3.setMargin(true);
		
		// question_competence
		question_competence = new Label();
		question_competence.setImmediate(false);
		question_competence.setWidth("-1px");
		question_competence.setHeight("-1px");
		question_competence.setValue("Voulez-vous choisir vos compétences ?");
		verticalLayout_3.addComponent(question_competence);
		verticalLayout_3.setComponentAlignment(question_competence,
				new Alignment(24));
		
		// horizontalLayout_1
		horizontalLayout_1 = buildHorizontalLayout_1();
		verticalLayout_3.addComponent(horizontalLayout_1);
		verticalLayout_3.setComponentAlignment(horizontalLayout_1,
				new Alignment(34));
		
		return verticalLayout_3;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_1() {
		// common part: create layout
		horizontalLayout_1 = new HorizontalLayout();
		horizontalLayout_1.setImmediate(false);
		horizontalLayout_1.setWidth("642px");
		horizontalLayout_1.setHeight("38px");
		horizontalLayout_1.setMargin(false);
		horizontalLayout_1.setSpacing(true);
		
		// btn_oui
		btn_oui = new Button();
		btn_oui.setCaption("Oui");
		btn_oui.setImmediate(true);
		btn_oui.setWidth("-1px");
		btn_oui.setHeight("-1px");
		horizontalLayout_1.addComponent(btn_oui);
		horizontalLayout_1.setComponentAlignment(btn_oui, new Alignment(34));
		
		// btn_non
		btn_non = new Button();
		btn_non.setCaption("Non");
		btn_non.setImmediate(true);
		btn_non.setWidth("-1px");
		btn_non.setHeight("-1px");
		horizontalLayout_1.addComponent(btn_non);
		horizontalLayout_1.setComponentAlignment(btn_non, new Alignment(33));
		
		return horizontalLayout_1;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_2() {
		// common part: create layout
		horizontalLayout_2 = new HorizontalLayout();
		horizontalLayout_2.setImmediate(false);
		horizontalLayout_2.setWidth("179px");
		horizontalLayout_2.setHeight("-1px");
		horizontalLayout_2.setMargin(false);
		horizontalLayout_2.setSpacing(true);
		
		// btn_enregistrer
		btn_enregistrer = new Button();
		btn_enregistrer.setCaption("Enregistrer");
		btn_enregistrer.setImmediate(true);
		btn_enregistrer.setWidth("-1px");
		btn_enregistrer.setHeight("-1px");
		horizontalLayout_2.addComponent(btn_enregistrer);
		
		// btn_annuler
		btn_annuler = new Button();
		btn_annuler.setCaption("Annuler");
		btn_annuler.setImmediate(true);
		btn_annuler.setWidth("-1px");
		btn_annuler.setHeight("26px");
		horizontalLayout_2.addComponent(btn_annuler);
		
		return horizontalLayout_2;
	}

	@AutoGenerated
	private Panel buildPanel_5() {
		// common part: create layout
		panel_5 = new Panel();
		panel_5.setImmediate(false);
		panel_5.setWidth("705px");
		panel_5.setHeight("100px");
		
		// verticalLayout_5
		verticalLayout_5 = buildVerticalLayout_5();
		panel_5.setContent(verticalLayout_5);
		
		return panel_5;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_5() {
		// common part: create layout
		verticalLayout_5 = new VerticalLayout();
		verticalLayout_5.setImmediate(false);
		verticalLayout_5.setWidth("100.0%");
		verticalLayout_5.setHeight("100.0%");
		verticalLayout_5.setMargin(false);
		
		// horizontalLayout_3
		horizontalLayout_3 = buildHorizontalLayout_3();
		verticalLayout_5.addComponent(horizontalLayout_3);
		verticalLayout_5.setComponentAlignment(horizontalLayout_3,
				new Alignment(20));
		
		// btn_ok
		btn_ok = new Button();
		btn_ok.setCaption("OK");
		btn_ok.setImmediate(true);
		btn_ok.setWidth("-1px");
		btn_ok.setHeight("-1px");
		verticalLayout_5.addComponent(btn_ok);
		verticalLayout_5.setComponentAlignment(btn_ok, new Alignment(20));
		
		return verticalLayout_5;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_3() {
		// common part: create layout
		horizontalLayout_3 = new HorizontalLayout();
		horizontalLayout_3.setImmediate(false);
		horizontalLayout_3.setWidth("701px");
		horizontalLayout_3.setHeight("59px");
		horizontalLayout_3.setMargin(true);
		
		// categorie
		categorie = new Label();
		categorie.setImmediate(false);
		categorie.setWidth("-1px");
		categorie.setHeight("-1px");
		categorie.setValue("Catégorie :    ");
		horizontalLayout_3.addComponent(categorie);
		horizontalLayout_3.setComponentAlignment(categorie, new Alignment(6));
		
		// categorie_list
		categorie_list = new NativeSelect();
		categorie_list.setImmediate(false);
		categorie_list.setWidth("-1px");
		categorie_list.setHeight("-1px");
		horizontalLayout_3.addComponent(categorie_list);
		
		// concept
		concept = new Label();
		concept.setImmediate(false);
		concept.setWidth("-1px");
		concept.setHeight("-1px");
		concept.setValue("Concept :    ");
		horizontalLayout_3.addComponent(concept);
		horizontalLayout_3.setComponentAlignment(concept, new Alignment(6));
		
		// concept_list
		concept_list = new NativeSelect();
		concept_list.setImmediate(false);
		concept_list.setWidth("-1px");
		concept_list.setHeight("-1px");
		horizontalLayout_3.addComponent(concept_list);
		
		// outil_list
		outil_list = new NativeSelect();
		outil_list.setImmediate(false);
		outil_list.setWidth("-1px");
		outil_list.setHeight("-1px");
		horizontalLayout_3.addComponent(outil_list);
		
		// outil
		outil = new Label();
		outil.setImmediate(false);
		outil.setWidth("-1px");
		outil.setHeight("-1px");
		outil.setValue("Outil :     ");
		horizontalLayout_3.addComponent(outil);
		horizontalLayout_3.setComponentAlignment(outil, new Alignment(6));
		
		return horizontalLayout_3;
	}

	@AutoGenerated
	private Panel buildPanel_1() {
		// common part: create layout
		panel_1 = new Panel();
		panel_1.setImmediate(false);
		panel_1.setWidth("300px");
		panel_1.setHeight("222px");
		
		// verticalLayout_1
		verticalLayout_1 = buildVerticalLayout_1();
		panel_1.setContent(verticalLayout_1);
		
		return panel_1;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_1() {
		// common part: create layout
		verticalLayout_1 = new VerticalLayout();
		verticalLayout_1.setImmediate(false);
		verticalLayout_1.setWidth("100.0%");
		verticalLayout_1.setHeight("100.3%");
		verticalLayout_1.setMargin(true);
		
		// embedded_1
		embedded_1 = new Embedded();
		embedded_1.setImmediate(false);
		embedded_1.setWidth("25px");
		embedded_1.setHeight("25px");
		embedded_1.setSource(new ExternalResource(
				"http://belleile.voila.net/Etoile.png"));
		embedded_1.setType(1);
		embedded_1.setMimeType("image/png");
		verticalLayout_1.addComponent(embedded_1);
		
		// horizontalLayout_4
		horizontalLayout_4 = buildHorizontalLayout_4();
		verticalLayout_1.addComponent(horizontalLayout_4);
		
		// horizontalLayout_5
		horizontalLayout_5 = buildHorizontalLayout_5();
		verticalLayout_1.addComponent(horizontalLayout_5);
		
		// horizontalLayout_6
		horizontalLayout_6 = buildHorizontalLayout_6();
		verticalLayout_1.addComponent(horizontalLayout_6);
		
		// horizontalLayout_7
		horizontalLayout_7 = buildHorizontalLayout_7();
		verticalLayout_1.addComponent(horizontalLayout_7);
		
		// horizontalLayout_8
		horizontalLayout_8 = buildHorizontalLayout_8();
		verticalLayout_1.addComponent(horizontalLayout_8);
		verticalLayout_1.setComponentAlignment(horizontalLayout_8,
				new Alignment(24));
		
		return verticalLayout_1;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_4() {
		// common part: create layout
		horizontalLayout_4 = new HorizontalLayout();
		horizontalLayout_4.setImmediate(false);
		horizontalLayout_4.setWidth("-1px");
		horizontalLayout_4.setHeight("-1px");
		horizontalLayout_4.setMargin(false);
		
		// embedded_3
		embedded_3 = new Embedded();
		embedded_3.setImmediate(false);
		embedded_3.setWidth("25px");
		embedded_3.setHeight("25px");
		embedded_3.setSource(new ExternalResource(
				"http://belleile.voila.net/Etoile.png"));
		embedded_3.setType(1);
		embedded_3.setMimeType("image/png");
		horizontalLayout_4.addComponent(embedded_3);
		
		// embedded_4
		embedded_4 = new Embedded();
		embedded_4.setImmediate(false);
		embedded_4.setWidth("25px");
		embedded_4.setHeight("25px");
		embedded_4.setSource(new ExternalResource(
				"http://belleile.voila.net/Etoile.png"));
		embedded_4.setType(1);
		embedded_4.setMimeType("image/png");
		horizontalLayout_4.addComponent(embedded_4);
		
		return horizontalLayout_4;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_5() {
		// common part: create layout
		horizontalLayout_5 = new HorizontalLayout();
		horizontalLayout_5.setImmediate(false);
		horizontalLayout_5.setWidth("-1px");
		horizontalLayout_5.setHeight("-1px");
		horizontalLayout_5.setMargin(false);
		
		// embedded_5
		embedded_5 = new Embedded();
		embedded_5.setImmediate(false);
		embedded_5.setWidth("25px");
		embedded_5.setHeight("25px");
		embedded_5.setSource(new ExternalResource(
				"http://belleile.voila.net/Etoile.png"));
		embedded_5.setType(1);
		embedded_5.setMimeType("image/png");
		horizontalLayout_5.addComponent(embedded_5);
		
		// embedded_7
		embedded_7 = new Embedded();
		embedded_7.setImmediate(false);
		embedded_7.setWidth("25px");
		embedded_7.setHeight("25px");
		embedded_7.setSource(new ExternalResource(
				"http://belleile.voila.net/Etoile.png"));
		embedded_7.setType(1);
		embedded_7.setMimeType("image/png");
		horizontalLayout_5.addComponent(embedded_7);
		
		// embedded_6
		embedded_6 = new Embedded();
		embedded_6.setImmediate(false);
		embedded_6.setWidth("25px");
		embedded_6.setHeight("25px");
		embedded_6.setSource(new ExternalResource(
				"http://belleile.voila.net/Etoile.png"));
		embedded_6.setType(1);
		embedded_6.setMimeType("image/png");
		horizontalLayout_5.addComponent(embedded_6);
		
		return horizontalLayout_5;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_6() {
		// common part: create layout
		horizontalLayout_6 = new HorizontalLayout();
		horizontalLayout_6.setImmediate(false);
		horizontalLayout_6.setWidth("-1px");
		horizontalLayout_6.setHeight("-1px");
		horizontalLayout_6.setMargin(false);
		
		// embedded_8
		embedded_8 = new Embedded();
		embedded_8.setImmediate(false);
		embedded_8.setWidth("25px");
		embedded_8.setHeight("25px");
		embedded_8.setSource(new ExternalResource(
				"http://belleile.voila.net/Etoile.png"));
		embedded_8.setType(1);
		embedded_8.setMimeType("image/png");
		horizontalLayout_6.addComponent(embedded_8);
		
		// embedded_11
		embedded_11 = new Embedded();
		embedded_11.setImmediate(false);
		embedded_11.setWidth("25px");
		embedded_11.setHeight("25px");
		embedded_11.setSource(new ExternalResource(
				"http://belleile.voila.net/Etoile.png"));
		embedded_11.setType(1);
		embedded_11.setMimeType("image/png");
		horizontalLayout_6.addComponent(embedded_11);
		
		// embedded_10
		embedded_10 = new Embedded();
		embedded_10.setImmediate(false);
		embedded_10.setWidth("25px");
		embedded_10.setHeight("25px");
		embedded_10.setSource(new ExternalResource(
				"http://belleile.voila.net/Etoile.png"));
		embedded_10.setType(1);
		embedded_10.setMimeType("image/png");
		horizontalLayout_6.addComponent(embedded_10);
		
		// embedded_9
		embedded_9 = new Embedded();
		embedded_9.setImmediate(false);
		embedded_9.setWidth("25px");
		embedded_9.setHeight("25px");
		embedded_9.setSource(new ExternalResource(
				"http://belleile.voila.net/Etoile.png"));
		embedded_9.setType(1);
		embedded_9.setMimeType("image/png");
		horizontalLayout_6.addComponent(embedded_9);
		
		return horizontalLayout_6;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_7() {
		// common part: create layout
		horizontalLayout_7 = new HorizontalLayout();
		horizontalLayout_7.setImmediate(false);
		horizontalLayout_7.setWidth("-1px");
		horizontalLayout_7.setHeight("-1px");
		horizontalLayout_7.setMargin(false);
		
		// embedded_16
		embedded_16 = new Embedded();
		embedded_16.setImmediate(false);
		embedded_16.setWidth("25px");
		embedded_16.setHeight("25px");
		embedded_16.setSource(new ExternalResource(
				"http://belleile.voila.net/Etoile.png"));
		embedded_16.setType(1);
		embedded_16.setMimeType("image/png");
		horizontalLayout_7.addComponent(embedded_16);
		
		// embedded_13
		embedded_13 = new Embedded();
		embedded_13.setImmediate(false);
		embedded_13.setWidth("25px");
		embedded_13.setHeight("25px");
		embedded_13.setSource(new ExternalResource(
				"http://belleile.voila.net/Etoile.png"));
		embedded_13.setType(1);
		embedded_13.setMimeType("image/png");
		horizontalLayout_7.addComponent(embedded_13);
		
		// embedded_15
		embedded_15 = new Embedded();
		embedded_15.setImmediate(false);
		embedded_15.setWidth("25px");
		embedded_15.setHeight("25px");
		embedded_15.setSource(new ExternalResource(
				"http://belleile.voila.net/Etoile.png"));
		embedded_15.setType(1);
		embedded_15.setMimeType("image/png");
		horizontalLayout_7.addComponent(embedded_15);
		
		// embedded_14
		embedded_14 = new Embedded();
		embedded_14.setImmediate(false);
		embedded_14.setWidth("25px");
		embedded_14.setHeight("25px");
		embedded_14.setSource(new ExternalResource(
				"http://belleile.voila.net/Etoile.png"));
		embedded_14.setType(1);
		embedded_14.setMimeType("image/png");
		horizontalLayout_7.addComponent(embedded_14);
		
		// embedded_12
		embedded_12 = new Embedded();
		embedded_12.setImmediate(false);
		embedded_12.setWidth("25px");
		embedded_12.setHeight("25px");
		embedded_12.setSource(new ExternalResource(
				"http://belleile.voila.net/Etoile.png"));
		embedded_12.setType(1);
		embedded_12.setMimeType("image/png");
		horizontalLayout_7.addComponent(embedded_12);
		
		return horizontalLayout_7;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_8() {
		// common part: create layout
		horizontalLayout_8 = new HorizontalLayout();
		horizontalLayout_8.setImmediate(false);
		horizontalLayout_8.setWidth("-1px");
		horizontalLayout_8.setHeight("-1px");
		horizontalLayout_8.setMargin(true);
		horizontalLayout_8.setSpacing(true);
		
		// annul_note
		annul_note = new Button();
		annul_note.setCaption("Annuler");
		annul_note.setImmediate(true);
		annul_note.setWidth("-1px");
		annul_note.setHeight("-1px");
		horizontalLayout_8.addComponent(annul_note);
		
		// valid_note
		valid_note = new Button();
		valid_note.setCaption("Valider");
		valid_note.setImmediate(true);
		valid_note.setWidth("-1px");
		valid_note.setHeight("-1px");
		horizontalLayout_8.addComponent(valid_note);
		
		return horizontalLayout_8;
	}

}
