---------------------------
-- SUPPRESSION DES INDEX --
---------------------------
DROP INDEX COLLEAGUEIDX1;
DROP INDEX CATEGORYIDX;
DROP INDEX CONCEPTIDX1;
DROP INDEX CONCEPTIDX2;
DROP INDEX TOOLIDX1;
DROP INDEX TOOLIDX2;
DROP INDEX OBJECTIVEIDX;
DROP INDEX MISSIONIDX1;
DROP INDEX MISSIONIDX2;
COMMIT;

--------------------
-- TABLE CLIENT --
--------------------
DROP TABLE CLIENT CASCADE CONSTRAINTS;

CREATE TABLE CLIENT
(
	CLIENT_ID     NUMBER(10) NOT NULL,
	CLIENT_NAME   VARCHAR2(30) NOT NULL
)
TABLESPACE tmp00dta;

COMMENT ON TABLE CLIENT IS 'Table des clients';

-----------------------
-- SEQUENCE CREATION --
-----------------------
DROP SEQUENCE SEQCLIENT;
CREATE SEQUENCE SEQCLIENT MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 1 NOCACHE;
COMMIT;


--------------------
-- TABLE PROFILE --
--------------------
DROP TABLE PROFILE CASCADE CONSTRAINTS;

CREATE TABLE PROFILE
(
	PROFILE_ID      NUMBER(3,0)  NOT NULL,
	PROFILE_TYPE    VARCHAR2(20) NOT NULL
)
TABLESPACE tmp00dta;

COMMENT ON TABLE PROFILE IS 'Table des types de profil';

-----------------------
-- SEQUENCE CREATION --
-----------------------
DROP SEQUENCE SEQPROFILE;
CREATE SEQUENCE SEQPROFILE MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 1 NOCACHE;
COMMIT;

-----------------------------
-- TABLE BUSINESS_ENGINEER --
-----------------------------
DROP TABLE BUSINESS_ENGINEER CASCADE CONSTRAINTS;

CREATE TABLE BUSINESS_ENGINEER
(
	B_ENGINEER_ID    	NUMBER(10,0)  NOT NULL,
	FIRST_NAME          VARCHAR2(40) NOT NULL,
	LAST_NAME   		VARCHAR2(40) NOT NULL,
	BUSINESS_UNIT       VARCHAR2(40) NOT NULL
)
TABLESPACE tmp00dta;

COMMENT ON TABLE BUSINESS_ENGINEER IS 'Table des Ingénieurs d Affaire';

-----------------------
-- SEQUENCE CREATION --
-----------------------
DROP SEQUENCE SEQBUSINESS_ENGINEER;
CREATE SEQUENCE SEQBUSINESS_ENGINEER MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 1 NOCACHE;
COMMIT;


---------------------
-- TABLE COLLEAGUE --
---------------------
DROP TABLE COLLEAGUE CASCADE CONSTRAINTS;

CREATE TABLE COLLEAGUE
(
	COLLEAGUE_ID      NUMBER(10,0)    NOT NULL,
	MANAGER_ID   	  NUMBER(10,0) ,
	PROFILE_ID    	  NUMBER(3,0)    NOT NULL,
	LAST_NAME    	  VARCHAR2(30)   NOT NULL,
	FIRST_NAME   	  VARCHAR2(30)   NOT NULL, 
	EMAIL        	  VARCHAR2(50)   NOT NULL,
	PHONE        	  NUMBER(10,0),
	EMPLOYMENT_DATE   DATE           NOT NULL,
	EXPERIENCE        NUMBER(2,0)    NOT NULL,
	B_ENGINEER_ID	  NUMBER(10,0)
)
TABLESPACE tmp00dta;

COMMENT ON TABLE COLLEAGUE IS 'Table des collaborateurs';

-----------------------
-- SEQUENCE CREATION --
-----------------------
DROP SEQUENCE SEQCOLLEAGUE;
CREATE SEQUENCE SEQCOLLEAGUE MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 1 NOCACHE;
COMMIT;

--------------------
-- TABLE AUTHENTICATION --
--------------------
DROP TABLE AUTHENTICATION CASCADE CONSTRAINTS;

CREATE TABLE AUTHENTICATION
(	
	LOGIN   VARCHAR2(50) 		   NOT NULL,
	PASSWORD   VARCHAR2(50)        NOT NULL
	COLLEAGUE_ID  NUMBER(10,0)      NOT NULL,
	ROLE_ID    NUMBER(3,0)         NOT NULL,
)
TABLESPACE tmp00dta;

COMMENT ON TABLE AUTHENTICATION IS 'Table des authentifications';
COMMIT;


--------------------
-- TABLE USER_ROLE --
--------------------
DROP TABLE USER_ROLE CASCADE CONSTRAINTS;

CREATE TABLE USER_ROLE
(	
	ROLE_ID  NUMBER(3,0) NOT NULL,
	LABEL   VARCHAR2(50) NOT NULL
)
TABLESPACE tmp00dta;

COMMENT ON TABLE USER_ROLE IS 'Table des rôles';

-----------------------
-- SEQUENCE CREATION --
-----------------------
DROP SEQUENCE SEQROL;
CREATE SEQUENCE SEQROL MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 1 NOCACHE;
COMMIT;


--------------------
-- TABLE COLLEAGUE_MANAGER_OBJ --
--------------------
DROP TABLE COLLEAGUE_MANAGER_OBJ CASCADE CONSTRAINTS;

CREATE TABLE COLLEAGUE_MANAGER_OBJ
(
	COLLEAGUE_ID   NUMBER(10,0) NOT NULL,
	MANAGER_ID     NUMBER(10,0) NOT NULL,
	OBJECTIVE_ID   NUMBER(10,0) NOT NULL,
	EA_DATE        DATE NOT NULL,
	EA_DOC         BLOB
)
TABLESPACE tmp00dta;

COMMENT ON TABLE COLLEAGUE_MANAGER_OBJ IS 'Table de relation entre un CM, un collaborateur et un EA';

-----------------------
-- SEQUENCE CREATION --
-----------------------
DROP SEQUENCE SEQCOLLEAGUE_MANAGER_OBJ;
CREATE SEQUENCE SEQCOLLEAGUE_MANAGER_OBJ MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 1 NOCACHE;
COMMIT;

--------------------
-- TABLE CATEGORY --
--------------------
DROP TABLE CATEGORY CASCADE CONSTRAINTS;

CREATE TABLE CATEGORY
(
	CATEGORY_ID     NUMBER(6,0)  NOT NULL,
	CATEGORY_NAME   VARCHAR2(20) NOT NULL
)
TABLESPACE tmp00dta;

COMMENT ON TABLE CATEGORY IS 'Table des Catégories';

-----------------------
-- SEQUENCE CREATION --
-----------------------
DROP SEQUENCE SEQCATEGORY;
CREATE SEQUENCE SEQCATEGORY MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 1 NOCACHE;
COMMIT;

--------------------
-- TABLE CONCEPT --
--------------------
DROP TABLE CONCEPT CASCADE CONSTRAINTS;

CREATE TABLE CONCEPT
(
	CONCEPT_ID    NUMBER(6,0)  NOT NULL,
	CATEGORY_ID   NUMBER(6,0)  NOT NULL,
	CONCEPT_NAME  VARCHAR2(20) NOT NULL
)
TABLESPACE tmp00dta;

COMMENT ON TABLE CONCEPT IS 'Table des concepts';

-----------------------
-- SEQUENCE CREATION --
-----------------------
DROP SEQUENCE SEQCONCEPT;
CREATE SEQUENCE SEQCONCEPT MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 1 NOCACHE;
COMMIT;

--------------------
-- TABLE TOOL --
--------------------
DROP TABLE TOOL CASCADE CONSTRAINTS;

CREATE TABLE TOOL
(
	TOOL_ID         NUMBER(6,0)  NOT NULL,
	CONCEPT_ID      NUMBER(6,0)  NOT NULL,
	TOOL_NAME       VARCHAR2(30) NOT NULL
)
TABLESPACE tmp00dta;

COMMENT ON TABLE TOOL IS 'Table des outils';

-----------------------
-- SEQUENCE CREATION --
-----------------------
DROP SEQUENCE SEQTOOL;

CREATE SEQUENCE SEQTOOL MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 1 NOCACHE;

COMMIT;

-----------
-- TABLE SKILL --
-----------
DROP TABLE SKILL CASCADE CONSTRAINTS;

CREATE TABLE SKILL
(
	COLLEAGUE_ID  	NUMBER(10) NOT NULL,
	TOOL_ID    		NUMBER(6) NOT NULL,
	USE_FREQUENCY   NUMBER(1) NOT NULL,
	NO_USING_TIME   NUMBER(1) NOT NULL,
	SCORE      		NUMBER(1) NOT NULL
)
TABLESPACE tmp00dta;

COMMENT ON TABLE SKILL IS 'Table des compétences';

-----------------------
-- SEQUENCE CREATION --
-----------------------
DROP SEQUENCE SEQSKILL;
CREATE SEQUENCE SEQSKILL MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 1 NOCACHE;
COMMIT;


--------------------
-- TABLE MISSION --
--------------------
DROP TABLE MISSION CASCADE CONSTRAINTS;

CREATE TABLE MISSION
(
	MISSION_ID     NUMBER(10)    NOT NULL,
	COLLEAGUE_ID   NUMBER(10)    NOT NULL,
	TITLE		   VARCHAR2(60) NOT NULL,
	PLACE		   VARCHAR2(60) NOT NULL,
	CLIENT_ID      NUMBER(10,0)  NOT NULL,
	NOTES		   CLOB,
	START_DATE     DATE         NOT NULL,
	END_DATE       DATE
)
TABLESPACE tmp00dta;

COMMENT ON TABLE MISSION IS 'Table des missions';

-----------------------
-- SEQUENCE CREATION --
-----------------------
DROP SEQUENCE SEQMISSION;
CREATE SEQUENCE SEQMISSION MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 1 NOCACHE;
COMMIT;


------------------------
-- TABLE MISSION_TOOL--
------------------------

DROP TABLE MISSION_TOOL;

CREATE TABLE MISSION_TOOL
(	MISSION_ID NUMBER(10,0) NOT NULL,  
	TOOL_ID NUMBER(6,0) NOT NULL
)
TABLESPACE tmp00dta;

COMMENT ON TABLE MISSION_TOOL IS 'Table associant les missions aux outils';

--------------------
-- TABLE OBJECTIVE --
--------------------
DROP TABLE OBJECTIVE CASCADE CONSTRAINTS;

CREATE TABLE OBJECTIVE
(
	OBJECTIVE_ID      NUMBER(10) NOT NULL,
	TARGET_DATE       DATE
)
TABLESPACE tmp00dta;

COMMENT ON TABLE OBJECTIVE IS 'Table des objectifs des EA';

-----------------------
-- SEQUENCE CREATION --
-----------------------
DROP SEQUENCE SEQOBJECTIVE;
CREATE SEQUENCE SEQOBJECTIVE MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 1 NOCACHE;
COMMIT;


--------------------
-- TABLE TASK --
--------------------
DROP TABLE TASK CASCADE CONSTRAINTS;

CREATE TABLE TASK
(
	TASK_ID      NUMBER(10)    NOT NULL,
	NAME         VARCHAR2(10) NOT NULL,
	TASK_TYPE    VARCHAR2(10) NOT NULL,
	TARGET_DATE  DATE,
	PRIORITY     NUMBER(1),
	EFFORT       NUMBER(1)  
)
TABLESPACE tmp00dta;

COMMENT ON TABLE TASK IS 'Table des tâches relative à l''atteinte d''un objectif';

-----------------------
-- SEQUENCE CREATION --
-----------------------
DROP SEQUENCE SEQTASK;
CREATE SEQUENCE SEQTASK MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 1 NOCACHE;
COMMIT;


--------------------
-- TABLE OBJECTIVE_TASK --
--------------------
DROP TABLE OBJECTIVE_TASK CASCADE CONSTRAINTS;

CREATE TABLE OBJECTIVE_TASK
(
	OBJECTIVE_ID  NUMBER(10) NOT NULL,
	TASK_ID       NUMBER(10) NOT NULL
)
TABLESPACE tmp00dta;

COMMENT ON TABLE OBJECTIVE_TASK IS 'Table de relation entre des objectifs et des tâches';

-----------------------
-- SEQUENCE CREATION --
-----------------------
DROP SEQUENCE SEQOBJECTIVE_TASK;
CREATE SEQUENCE SEQOBJECTIVE_TASK MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 1 NOCACHE;
COMMIT;

------------------------
-- CREATION DES INDEX --
------------------------
CREATE INDEX COLLEAGUEIDX1 ON COLLEAGUE (COLLEAGUE_ID) TABLESPACE tmp00idx;
CREATE INDEX CATEGORYIDX ON CATEGORY (CATEGORY_ID) TABLESPACE tmp00idx;
CREATE INDEX CONCEPTIDX1 ON CONCEPT (CONCEPT_ID) TABLESPACE tmp00idx;
CREATE INDEX CONCEPTIDX2 ON CONCEPT (CATEGORY_ID) TABLESPACE tmp00idx;
CREATE INDEX TOOLIDX1 ON TOOL (TOOL_ID) TABLESPACE tmp00idx;
CREATE INDEX TOOLIDX2 ON TOOL (CONCEPT_ID) TABLESPACE tmp00idx;
CREATE INDEX OBJECTIVEIDX ON OBJECTIVE (OBJECTIVE_ID) TABLESPACE tmp00idx;
CREATE INDEX MISSIONIDX1 ON MISSION (MISSION_ID) TABLESPACE tmp00idx;
CREATE INDEX MISSIONIDX2 ON MISSION (COLLEAGUE_ID) TABLESPACE tmp00idx;
COMMIT;