	
insert into TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME) values (1,1,'Google Guice');	
insert into TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME) values (2,1,'PicoContainer');	
insert into TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME) values (3,1,'Spring');	
insert into TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME) values (4,2,'Hibernate');	
insert into TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME) values (5,2,'iBATIS');	
insert into TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME) values (6,2,'jOOQ');	
insert into TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME) values (7,3,'Castel Windsor');	
insert into TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME) values (8,3,'StructureMap');	
insert into TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME) values (9,3,'Spring.NET');	
insert into TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME) values (10,3,'Autofac');	
insert into TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME) values (11,3,'Unity');	
insert into TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME) values (12,3,'Puzzle.Nfactory');	
insert into TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME) values (13,3,'Ninject');	
insert into TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME) values (14,3,'S2Container.NET');	
insert into TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME) values (15,3,'PicoContainer.NET');	
insert into TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME) values (16,3,'LinFu');	
insert into TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME) values (17,4,'Microsoft ADO.NET');	
insert into TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME) values (18,4,'Microsoft Enterprise Library');	
insert into TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME) values (19,4,'CustomORM');	
insert into TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME) values (20,5,'Doctrine');	
insert into TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME) values (21,5,'Propel');	
insert into TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME) values (22,5,'PHPMyObject');	
insert into TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME) values (23,5,'JDAO ');	
insert into TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME) values (24,6,'Drip');	
insert into TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME) values (25,6,'Garden');	
insert into TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME) values (26,6,'Solar');	
insert into TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME) values (27,6,'Phemto');	
insert into TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME) values (28,6,'Seasar');	
insert into TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME) values (29,6,'ClawPHP');	
insert into TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME) values (30,6,'WACT');	
insert into TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME) values (31,7,'Windsor');	
insert into TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME) values (32,8,'Nhibernate');	
insert into TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME) values (33,8,'Subsoniq');	
insert into TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME) values (34,8,'Castle ActiveRecord');	
insert into TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME) values (35,8,'NH');	
insert into TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME) values (36,8,'EF');	
insert into TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME) values (37,8,'LLBLGenPro');	
insert into TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME) values (38,9,'SQL');	
insert into TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME) values (39,9,'DB2');	
insert into TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME) values (40,9,'IBM Informix ');	
insert into TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME) values (41,9,'IBM Cloudscape ');	
insert into TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME) values (42,9,'SQL Server');	
insert into TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME) values (43,9,'Access');	
insert into TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME) values (44,9,'Oracle');	
insert into TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME) values (45,9,'Hyperion EssBase');	
insert into TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME) values (46,9,'MySQL');	
insert into TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME) values (47,9,'Java DB');	
insert into TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME) values (48,9,'PostgreSQL');	
insert into TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME) values (49,9,'Sybase');	
insert into TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME) values (50,9,'SQLite');	
insert into TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME) values (51,12,'ALM');	
insert into TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME) values (52,12,'UML');	
insert into TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME) values (53,12,'Merise');	
insert into TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME) values (54,10,'Junit');	
insert into TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME) values (55,11,'Nunit');	
insert into TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME) values (56,13,'Sonar');	
insert into TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME) values (57,14,'Word');	
insert into TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME) values (58,14,'Excel');	
insert into TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME) values (59,15,'Icalendar');	
insert into TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME) values (60,15,'Evernote');	
insert into TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME) values (61,16,'Notepad++');	
insert into TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME) values (62,16,'BlocNote');	
insert into TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME) values (63,17,'Agenda Lite');	
insert into TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME) values (64,17,'LockCalendar ');	
