insert into COLLABORATOR (COLLAB_ID, MANAGER_ID, PROFILE_ID, LAST_NAME, FIRST_NAME, EMAIL, PHONE, EMPLOYMENT_DATE, EXPERIENCE, BUSINESS_ENGINEER) 								
values (1,1,6,'COLLET','Julien','j.collet@novedia-solution.com',102030405,'23/04/2010',1,'Renaud MIGNE');								
insert into COLLABORATOR (COLLAB_ID, MANAGER_ID, PROFILE_ID, LAST_NAME, FIRST_NAME, EMAIL, PHONE, EMPLOYMENT_DATE, EXPERIENCE, BUSINESS_ENGINEER) 								
values (2,1,5,'MOUMBE','Elisé','e.moumbe@novedia-solution.com',102030415,'23/04/2010',2,'Julie VIGNERON');								
insert into COLLABORATOR (COLLAB_ID, MANAGER_ID, PROFILE_ID, LAST_NAME, FIRST_NAME, EMAIL, PHONE, EMPLOYMENT_DATE, EXPERIENCE, BUSINESS_ENGINEER) 								
values (3,3,6,'GUILLEMAIN','Vanessa','v.guillemain@novedia-solution.com',102030425,'23/04/2010',3,'Déborah ATTIAS');								
insert into COLLABORATOR (COLLAB_ID, MANAGER_ID, PROFILE_ID, LAST_NAME, FIRST_NAME, EMAIL, PHONE, EMPLOYMENT_DATE, EXPERIENCE, BUSINESS_ENGINEER) 								
values (4,3,4,'CHAUVIE','Olivier','o.chauvie@novedia-solution.com',102030435,'23/04/2010',8,'Renaud MIGNE');								
insert into COLLABORATOR (COLLAB_ID, MANAGER_ID, PROFILE_ID, LAST_NAME, FIRST_NAME, EMAIL, PHONE, EMPLOYMENT_DATE, EXPERIENCE, BUSINESS_ENGINEER) 								
values (5,4,3,'BRULATOUT','Eric','e.brulatout@novedia-solution.com',102030445,'23/04/2010',7,'Julie VIGNERON');								
insert into COLLABORATOR (COLLAB_ID, MANAGER_ID, PROFILE_ID, LAST_NAME, FIRST_NAME, EMAIL, PHONE, EMPLOYMENT_DATE, EXPERIENCE, BUSINESS_ENGINEER) 								
values (6,2,2,'CAUMARTIN','Régine','r.caumartin@novedia-solution.com',102030455,'23/04/2010',6,'Déborah ATTIAS');								
insert into COLLABORATOR (COLLAB_ID, MANAGER_ID, PROFILE_ID, LAST_NAME, FIRST_NAME, EMAIL, PHONE, EMPLOYMENT_DATE, EXPERIENCE, BUSINESS_ENGINEER) 								
values (7,2,2,'ANGLADE','Mathias','m.anglade@novedia-solution.com',102030465,'23/04/2010',2,'Renaud MIGNE');								
insert into COLLABORATOR (COLLAB_ID, MANAGER_ID, PROFILE_ID, LAST_NAME, FIRST_NAME, EMAIL, PHONE, EMPLOYMENT_DATE, EXPERIENCE, BUSINESS_ENGINEER) 								
values (8,2,6,'THAI','Shien-Haur','s.thai@novedia-solution.com',102030475,'23/04/2010',4,'Julie VIGNERON');								
insert into COLLABORATOR (COLLAB_ID, MANAGER_ID, PROFILE_ID, LAST_NAME, FIRST_NAME, EMAIL, PHONE, EMPLOYMENT_DATE, EXPERIENCE, BUSINESS_ENGINEER) 								
values (9,4,3,'EYCHENNE','Patrick','p.eychenne@novedia-solution.com',102030485,'23/04/2010',6,'Déborah ATTIAS');								
insert into COLLABORATOR (COLLAB_ID, MANAGER_ID, PROFILE_ID, LAST_NAME, FIRST_NAME, EMAIL, PHONE, EMPLOYMENT_DATE, EXPERIENCE, BUSINESS_ENGINEER) 								
values (10,5,1,'ROBIN','Murielle','m.robin@novedia-solution.com',102030495,'23/04/2010',5,'Renaud MIGNE');								
insert into COLLABORATOR (COLLAB_ID, MANAGER_ID, PROFILE_ID, LAST_NAME, FIRST_NAME, EMAIL, PHONE, EMPLOYMENT_DATE, EXPERIENCE, BUSINESS_ENGINEER) 								
values (11,5,3,'RAVINE','Sandrine','s.ravine@novedia-solution.com',102030505,'23/04/2010',7,'Julie VIGNERON');								
insert into COLLABORATOR (COLLAB_ID, MANAGER_ID, PROFILE_ID, LAST_NAME, FIRST_NAME, EMAIL, PHONE, EMPLOYMENT_DATE, EXPERIENCE, BUSINESS_ENGINEER) 								
values (12,6,5,'LOET','Sylvie','s.loet@novedia-solution.com',102030515,'23/04/2010',9,'Renaud MIGNE');								
insert into COLLABORATOR (COLLAB_ID, MANAGER_ID, PROFILE_ID, LAST_NAME, FIRST_NAME, EMAIL, PHONE, EMPLOYMENT_DATE, EXPERIENCE, BUSINESS_ENGINEER) 								
values (13,1,3,'BERTON','Alexandre ','a.berton@novedia-solutions.com',102030525,'23/04/2010',1,'Renaud MIGNE');								
insert into COLLABORATOR (COLLAB_ID, MANAGER_ID, PROFILE_ID, LAST_NAME, FIRST_NAME, EMAIL, PHONE, EMPLOYMENT_DATE, EXPERIENCE, BUSINESS_ENGINEER) 								
values (14,1,5,'BOUDICH','Karim','k.boudich@novedia-solutions.com',102030535,'23/04/2010',2,'Julie VIGNERON');								
insert into COLLABORATOR (COLLAB_ID, MANAGER_ID, PROFILE_ID, LAST_NAME, FIRST_NAME, EMAIL, PHONE, EMPLOYMENT_DATE, EXPERIENCE, BUSINESS_ENGINEER) 								
values (15,3,5,'CHEVALIER','Isabelle','i.chevalier@novedia-solutions.com',102030545,'23/04/2010',3,'Déborah ATTIAS');								
insert into COLLABORATOR (COLLAB_ID, MANAGER_ID, PROFILE_ID, LAST_NAME, FIRST_NAME, EMAIL, PHONE, EMPLOYMENT_DATE, EXPERIENCE, BUSINESS_ENGINEER) 								
values (16,5,1,'Anne-lise','GALOT','al.galot@novedia-solutions.com',102030555,'23/04/2010',8,'Renaud MIGNE');								
insert into COLLABORATOR (COLLAB_ID, MANAGER_ID, PROFILE_ID, LAST_NAME, FIRST_NAME, EMAIL, PHONE, EMPLOYMENT_DATE, EXPERIENCE, BUSINESS_ENGINEER) 								
values (17,4,4,'Eric','FAUQUEMBERGUE','e.fauquembergue@novedia-solutions.com',102030565,'23/04/2010',7,'Julie VIGNERON');								
insert into COLLABORATOR (COLLAB_ID, MANAGER_ID, PROFILE_ID, LAST_NAME, FIRST_NAME, EMAIL, PHONE, EMPLOYMENT_DATE, EXPERIENCE, BUSINESS_ENGINEER) 								
values (18,1,5,'Sébastien','GERMOND','s.germond@novedia-solutions.com',102030575,'23/04/2010',6,'Déborah ATTIAS');								
insert into COLLABORATOR (COLLAB_ID, MANAGER_ID, PROFILE_ID, LAST_NAME, FIRST_NAME, EMAIL, PHONE, EMPLOYMENT_DATE, EXPERIENCE, BUSINESS_ENGINEER) 								
values (19,7,6,'Vincent','GRELIER','v.grelier@novedia-solutions.com',102030585,'23/04/2010',2,'Julie VIGNERON');								
insert into COLLABORATOR (COLLAB_ID, MANAGER_ID, PROFILE_ID, LAST_NAME, FIRST_NAME, EMAIL, PHONE, EMPLOYMENT_DATE, EXPERIENCE, BUSINESS_ENGINEER) 								
values (20,3,5,'Julien','LE GUENNEC','j.leguennec@novedia-solutions.com',102030595,'23/04/2010',4,'Déborah ATTIAS');								
insert into COLLABORATOR (COLLAB_ID, MANAGER_ID, PROFILE_ID, LAST_NAME, FIRST_NAME, EMAIL, PHONE, EMPLOYMENT_DATE, EXPERIENCE, BUSINESS_ENGINEER) 								
values (21,4,1,'Louis','ANDRIET','l.andriet@novedia-solutions.com',102030605,'23/04/2010',6,'Renaud MIGNE');								
insert into COLLABORATOR (COLLAB_ID, MANAGER_ID, PROFILE_ID, LAST_NAME, FIRST_NAME, EMAIL, PHONE, EMPLOYMENT_DATE, EXPERIENCE, BUSINESS_ENGINEER) 								
values (22,3,1,'Thierry','AVRIL','t.avril@novedia-solutions.com',102030615,'23/04/2010',5,'Julie VIGNERON');								
insert into COLLABORATOR (COLLAB_ID, MANAGER_ID, PROFILE_ID, LAST_NAME, FIRST_NAME, EMAIL, PHONE, EMPLOYMENT_DATE, EXPERIENCE, BUSINESS_ENGINEER) 								
values (23,1,1,'Johan','BONNEAU','j.bonneau@novedia-solutions.com',102030625,'23/04/2010',7,'Déborah ATTIAS');								
insert into COLLABORATOR (COLLAB_ID, MANAGER_ID, PROFILE_ID, LAST_NAME, FIRST_NAME, EMAIL, PHONE, EMPLOYMENT_DATE, EXPERIENCE, BUSINESS_ENGINEER) 								
values (24,7,3,'Guillaume','BALFIN','g.balfin@novedia-agency.com',102030635,'23/04/2010',9,'Renaud MIGNE');								
insert into COLLABORATOR (COLLAB_ID, MANAGER_ID, PROFILE_ID, LAST_NAME, FIRST_NAME, EMAIL, PHONE, EMPLOYMENT_DATE, EXPERIENCE, BUSINESS_ENGINEER) 								
values (25,3,5,'Paule','BOUADJIE','p.bouadjie@novedia-solutions.com',102030645,'23/04/2010',1,'Julie VIGNERON');								
insert into COLLABORATOR (COLLAB_ID, MANAGER_ID, PROFILE_ID, LAST_NAME, FIRST_NAME, EMAIL, PHONE, EMPLOYMENT_DATE, EXPERIENCE, BUSINESS_ENGINEER) 								
values (26,4,3,'Houda','BELMQADEM','h.belmqadem@novedia-decision.com',102030655,'23/04/2010',2,'Renaud MIGNE');								
insert into COLLABORATOR (COLLAB_ID, MANAGER_ID, PROFILE_ID, LAST_NAME, FIRST_NAME, EMAIL, PHONE, EMPLOYMENT_DATE, EXPERIENCE, BUSINESS_ENGINEER) 								
values (27,7,2,'Mickaël','HENRY','m.henry@novedia-solutions.com',102030665,'23/04/2010',3,'Renaud MIGNE');								
insert into COLLABORATOR (COLLAB_ID, MANAGER_ID, PROFILE_ID, LAST_NAME, FIRST_NAME, EMAIL, PHONE, EMPLOYMENT_DATE, EXPERIENCE, BUSINESS_ENGINEER) 								
values (28,3,1,'Amina','DEROUICH','a.derouich@novedia-decision.com',102030675,'23/04/2010',8,'Julie VIGNERON');								
insert into COLLABORATOR (COLLAB_ID, MANAGER_ID, PROFILE_ID, LAST_NAME, FIRST_NAME, EMAIL, PHONE, EMPLOYMENT_DATE, EXPERIENCE, BUSINESS_ENGINEER) 								
values (29,5,3,'Hélène','DREUX','h.dreux@novedia-solutions.com',102030685,'23/04/2010',7,'Déborah ATTIAS');								
insert into COLLABORATOR (COLLAB_ID, MANAGER_ID, PROFILE_ID, LAST_NAME, FIRST_NAME, EMAIL, PHONE, EMPLOYMENT_DATE, EXPERIENCE, BUSINESS_ENGINEER) 								
values (30,6,1,'Erwan','ALLIX','e.allix@novedia-solutions.com',102030695,'23/04/2010',6,'Renaud MIGNE');								
insert into COLLABORATOR (COLLAB_ID, MANAGER_ID, PROFILE_ID, LAST_NAME, FIRST_NAME, EMAIL, PHONE, EMPLOYMENT_DATE, EXPERIENCE, BUSINESS_ENGINEER) 								
values (31,2,3,'Jean','lou HUBERT','j.hubert@novedia-solutions.com',102030705,'23/04/2010',2,'Julie VIGNERON');								
insert into COLLABORATOR (COLLAB_ID, MANAGER_ID, PROFILE_ID, LAST_NAME, FIRST_NAME, EMAIL, PHONE, EMPLOYMENT_DATE, EXPERIENCE, BUSINESS_ENGINEER) 								
values (32,2,2,'Stéphane','PELLOT','s.pellot@novedia-solutions.com',102030715,'23/04/2010',4,'Renaud MIGNE');								
insert into COLLABORATOR (COLLAB_ID, MANAGER_ID, PROFILE_ID, LAST_NAME, FIRST_NAME, EMAIL, PHONE, EMPLOYMENT_DATE, EXPERIENCE, BUSINESS_ENGINEER) 								
values (33,5,6,'Sylvain','MERLET','s.merlet@novedia-solutions.com',102030725,'23/04/2010',6,'Renaud MIGNE');								
insert into COLLABORATOR (COLLAB_ID, MANAGER_ID, PROFILE_ID, LAST_NAME, FIRST_NAME, EMAIL, PHONE, EMPLOYMENT_DATE, EXPERIENCE, BUSINESS_ENGINEER) 								
values (34,6,1,'Mirana','MAESTRACCI','m.maestracci@novedia-solutions.com',102030735,'23/04/2010',5,'Julie VIGNERON');								
