insert into CATEGORY (CATEGORY_ID, CATEGORY_NAME) values (1, 'Java EE');
insert into CATEGORY (CATEGORY_ID, CATEGORY_NAME) values (1,'Java EE');
insert into CATEGORY (CATEGORY_ID, CATEGORY_NAME) values (2,'.NET');
insert into CATEGORY (CATEGORY_ID, CATEGORY_NAME) values (3,'PHP');
insert into CATEGORY (CATEGORY_ID, CATEGORY_NAME) values (4,'C#');
insert into CATEGORY (CATEGORY_ID, CATEGORY_NAME) values (5,'SGBD');
insert into CATEGORY (CATEGORY_ID, CATEGORY_NAME) values (6,'Conception');
insert into CATEGORY (CATEGORY_ID, CATEGORY_NAME) values (7,'Qualité');
insert into CATEGORY (CATEGORY_ID, CATEGORY_NAME) values (8,'AMOA');
insert into CATEGORY (CATEGORY_ID, CATEGORY_NAME) values (9,'PMO');
