insert into MANAGER (MANAGER_ID, PROFILE_ID, LAST_NAME, FIRST_NAME, EMAIL, PHONE, EMPLOYMENT_DATE, EXPERIENCE, BUSINESS_ENGINEER) 							
values (1,1,'MARIE-SAINTE','Jean-Max','j.marie-sainte@novediagroup.com',102030405,'23/04/2010',7,'Julie VIGNERON');							
insert into MANAGER (MANAGER_ID, PROFILE_ID, LAST_NAME, FIRST_NAME, EMAIL, PHONE, EMPLOYMENT_DATE, EXPERIENCE, BUSINESS_ENGINEER) 							
values (2,1,'GERME','Kelly','k.germe@novediagroup.com',102030405,'23/04/2010',11,'Renaud MIGNE');							
insert into MANAGER (MANAGER_ID, PROFILE_ID, LAST_NAME, FIRST_NAME, EMAIL, PHONE, EMPLOYMENT_DATE, EXPERIENCE, BUSINESS_ENGINEER) 							
values (3,5,'BONVOISIN','Sébastien','s.bonvoisin@novediagroup.com',102030405,'23/04/2010',8,'Deborah ATTIAS');							
insert into MANAGER (MANAGER_ID, PROFILE_ID, LAST_NAME, FIRST_NAME, EMAIL, PHONE, EMPLOYMENT_DATE, EXPERIENCE, BUSINESS_ENGINEER) 							
values (4,1,'BRULATOUT','Eric','e.brulatout@novediagroup.com',102030405,'23/04/2010',9,'Renaud MIGNE');							
insert into MANAGER (MANAGER_ID, PROFILE_ID, LAST_NAME, FIRST_NAME, EMAIL, PHONE, EMPLOYMENT_DATE, EXPERIENCE, BUSINESS_ENGINEER) 							
values (5,1,'ACKERMANN','Bruno','b.ackermann@novediagroup.com',102030405,'23/04/2010',12,'Renaud MIGNE');							
insert into MANAGER (MANAGER_ID, PROFILE_ID, LAST_NAME, FIRST_NAME, EMAIL, PHONE, EMPLOYMENT_DATE, EXPERIENCE, BUSINESS_ENGINEER) 							
values (6,3,'DANTO','Fanny','f.danto@novedia-solutions.com',102030405,'23/04/2010',5,'Julie VIGNERON');							
insert into MANAGER (MANAGER_ID, PROFILE_ID, LAST_NAME, FIRST_NAME, EMAIL, PHONE, EMPLOYMENT_DATE, EXPERIENCE, BUSINESS_ENGINEER) 							
values (7,3,'DEJONGHE','Xavier','x.dejonghe@novedia-solutions.com',102030405,'23/04/2010',6,'Julie VIGNERON');							
