---------------------------
--    DATA INSERTION     --
---------------------------
INSERT INTO TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME)
VALUES (1,1,'Google Guice');
INSERT INTO TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME)
VALUES (2,1,'PicoContainer');
INSERT INTO TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME)
VALUES (3,1,'Spring');
INSERT INTO TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME)
VALUES (4,2,'Hibernate');
INSERT INTO TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME)
VALUES (5,2,'iBATIS');
INSERT INTO TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME)
VALUES (6,2,'jOOQ');
INSERT INTO TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME)
VALUES (7,3,'Castel Windsor');
INSERT INTO TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME)
VALUES (8,3,'StructureMap');
INSERT INTO TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME)
VALUES (9,3,'Spring.NET');
INSERT INTO TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME)
VALUES (10,3,'Autofac');
INSERT INTO TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME)
VALUES (11,3,'Unity');
INSERT INTO TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME)
VALUES (12,3,'Puzzle.Nfactory');
INSERT INTO TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME)
VALUES (13,3,'Ninject');
INSERT INTO TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME)
VALUES (14,3,'S2Container.NET');
INSERT INTO TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME)
VALUES (15,3,'PicoContainer.NET');
INSERT INTO TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME)
VALUES (16,3,'LinFu');
INSERT INTO TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME)
VALUES (17,4,'Microsoft ADO.NET');
INSERT INTO TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME)
VALUES (18,4,'Microsoft Enterprise Library');
INSERT INTO TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME)
VALUES (19,4,'CustomORM');
INSERT INTO TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME)
VALUES (20,5,'Doctrine');
INSERT INTO TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME)
VALUES (21,5,'Propel');
INSERT INTO TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME)
VALUES (22,5,'PHPMyObject');
INSERT INTO TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME)
VALUES (23,5,'JDAO ');
INSERT INTO TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME)
VALUES (24,6,'Drip');
INSERT INTO TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME)
VALUES (25,6,'Garden');
INSERT INTO TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME)
VALUES (26,6,'Solar');
INSERT INTO TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME)
VALUES (27,6,'Phemto');
INSERT INTO TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME)
VALUES (28,6,'Seasar');
INSERT INTO TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME)
VALUES (29,6,'ClawPHP');
INSERT INTO TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME)
VALUES (30,6,'WACT');
INSERT INTO TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME)
VALUES (31,7,'Windsor');
INSERT INTO TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME)
VALUES (32,8,'Nhibernate');
INSERT INTO TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME)
VALUES (33,8,'Subsoniq');
INSERT INTO TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME)
VALUES (34,8,'Castle ActiveRecord');
INSERT INTO TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME)
VALUES (35,8,'NH');
INSERT INTO TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME)
VALUES (36,8,'EF');
INSERT INTO TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME)
VALUES (37,8,'LLBLGenPro');
INSERT INTO TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME)
VALUES (38,9,'SQL');
INSERT INTO TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME)
VALUES (39,9,'DB2');
INSERT INTO TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME)
VALUES (40,9,'IBM Informix ');
INSERT INTO TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME)
VALUES (41,9,'IBM Cloudscape ');
INSERT INTO TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME)
VALUES (42,9,'SQL Server');
INSERT INTO TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME)
VALUES (43,9,'Access');
INSERT INTO TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME)
VALUES (44,9,'Oracle');
INSERT INTO TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME)
VALUES (45,9,'Hyperion EssBase');
INSERT INTO TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME)
VALUES (46,9,'MySQL');
INSERT INTO TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME)
VALUES (47,9,'Java DB');
INSERT INTO TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME)
VALUES (48,9,'PostgreSQL');
INSERT INTO TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME)
VALUES (49,9,'Sybase');
INSERT INTO TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME)
VALUES (50,9,'SQLite');
INSERT INTO TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME)
VALUES (51,12,'ALM');
INSERT INTO TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME)
VALUES (52,12,'UML');
INSERT INTO TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME)
VALUES (53,12,'Merise');
INSERT INTO TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME)
VALUES (54,10,'Junit');
INSERT INTO TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME)
VALUES (55,11,'Nunit');
INSERT INTO TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME)
VALUES (56,13,'Sonar');
INSERT INTO TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME)
VALUES (57,14,'Word');
INSERT INTO TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME)
VALUES (58,14,'Excel');
INSERT INTO TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME)
VALUES (59,15,'Icalendar');
INSERT INTO TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME)
VALUES (60,15,'Evernote');
INSERT INTO TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME)
VALUES (61,16,'Notepad++');
INSERT INTO TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME)
VALUES (62,16,'BlocNote');
INSERT INTO TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME)
VALUES (63,17,'Agenda Lite');
INSERT INTO TOOL (TOOL_ID, CONCEPT_ID, TOOL_NAME)
VALUES (64,17,'LockCalendar ');
COMMIT;
