---------------------------
--    DATA INSERTION     --
---------------------------
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME)
VALUES (1,'Java EE');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME)
VALUES (2,'.NET');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME)
VALUES (3,'PHP');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME)
VALUES (4,'C#');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME)
VALUES (5,'SGBD');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME)
VALUES (6,'Conception');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME)
VALUES (7,'Qualité');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME)
VALUES (8,'AMOA');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME)
VALUES (9,'PMO');

COMMIT;

-----------------------
-- SEQUENCE UPDATE --
-----------------------
DROP SEQUENCE SEQCATEGORY;
CREATE SEQUENCE SEQCATEGORY MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 10 NOCACHE;

COMMIT;