---------------------------
--    DATA INSERTION     --
---------------------------
INSERT INTO CLIENT (CLIENT_ID,CLIENT_NAME) VALUES ('1','Orange');
INSERT INTO CLIENT (CLIENT_ID,CLIENT_NAME) VALUES ('2','Air France');
INSERT INTO CLIENT (CLIENT_ID,CLIENT_NAME) VALUES ('3','PSA');
INSERT INTO CLIENT (CLIENT_ID,CLIENT_NAME) VALUES ('4','Canal+');
INSERT INTO CLIENT (CLIENT_ID,CLIENT_NAME) VALUES ('5','Intent');
INSERT INTO CLIENT (CLIENT_ID,CLIENT_NAME) VALUES ('6','Total');
INSERT INTO CLIENT (CLIENT_ID,CLIENT_NAME) VALUES ('7','Mattel');
INSERT INTO CLIENT (CLIENT_ID,CLIENT_NAME) VALUES ('8','NavBoard');
INSERT INTO CLIENT (CLIENT_ID,CLIENT_NAME) VALUES ('9','Citroen');
INSERT INTO CLIENT (CLIENT_ID,CLIENT_NAME) VALUES ('10','France Télécom');
INSERT INTO CLIENT (CLIENT_ID,CLIENT_NAME) VALUES ('11','Hermès');
COMMIT;

-----------------------
-- SEQUENCE CREATION --
-----------------------
DROP SEQUENCE SEQCLIENT;
CREATE SEQUENCE SEQCLIENT MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 12 NOCACHE;

COMMIT;