---------------------------
--    DATA INSERTION     --
---------------------------
INSERT into CLIENT (CLIENT_ID,CLIENT_NAME) VALUES ('1','Orange');
INSERT into CLIENT (CLIENT_ID,CLIENT_NAME) VALUES ('2','Air France');
INSERT into CLIENT (CLIENT_ID,CLIENT_NAME) VALUES ('3','PSA');
INSERT into CLIENT (CLIENT_ID,CLIENT_NAME) VALUES ('4','Canal+');
INSERT into CLIENT (CLIENT_ID,CLIENT_NAME) VALUES ('5','Intent');
INSERT into CLIENT (CLIENT_ID,CLIENT_NAME) VALUES ('6','Total');
INSERT into CLIENT (CLIENT_ID,CLIENT_NAME) VALUES ('7','Mattel');
INSERT into CLIENT (CLIENT_ID,CLIENT_NAME) VALUES ('8','NavBoard');
INSERT into CLIENT (CLIENT_ID,CLIENT_NAME) VALUES ('9','Citroen');
INSERT into CLIENT (CLIENT_ID,CLIENT_NAME) VALUES ('10','France Télécom');
INSERT into CLIENT (CLIENT_ID,CLIENT_NAME) VALUES ('11','Hermès');
COMMIT;
