---------------------------
--    DATA INSERTION     --
---------------------------

INSERT INTO BUSINESS_ENGINEER (B_ENGINEER_ID, NAME)		VALUES (1,'Jean-lou HUBERT');
INSERT INTO BUSINESS_ENGINEER (B_ENGINEER_ID, NAME)		VALUES (2,'Jean BON');
INSERT INTO BUSINESS_ENGINEER (B_ENGINEER_ID, NAME)		VALUES (3,'Julie VIGNERON');
INSERT INTO BUSINESS_ENGINEER (B_ENGINEER_ID, NAME)		VALUES (4,'Déborah ATTIAS');
INSERT INTO BUSINESS_ENGINEER (B_ENGINEER_ID, NAME)		VALUES (5,'Renaud MIGNE');
INSERT INTO BUSINESS_ENGINEER (B_ENGINEER_ID, NAME)		VALUES (6,'Mirana MAESTRACCI');
INSERT INTO BUSINESS_ENGINEER (B_ENGINEER_ID, NAME)		VALUES (7,'Vanessa GUILLEMAIN');

COMMIT;

-----------------------
-- SEQUENCE UPDATE --
-----------------------
DROP SEQUENCE SEQBUSINESS_ENGINEER;
CREATE SEQUENCE SEQBUSINESS_ENGINEER MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 8 NOCACHE;

COMMIT;
