---------------------------
--    DATA INSERTION     --
---------------------------
INSERT INTO MANAGER (MANAGER_ID, PROFILE_ID, LAST_NAME, FIRST_NAME, EMAIL, PHONE, EMPLOYMENT_DATE, EXPERIENCE, BUSINESS_ENGINEER) 
VALUES (1,6,'MARIE-SAINTE','Jean-Max','j.marie-sainte@novediagroup.com',102030405,'23/04/2010',7,'Julie VIGNERON');
INSERT INTO MANAGER (MANAGER_ID, PROFILE_ID, LAST_NAME, FIRST_NAME, EMAIL, PHONE, EMPLOYMENT_DATE, EXPERIENCE, BUSINESS_ENGINEER) 
VALUES (2,2,'GERME','Kelly','k.germe@novediagroup.com',102030405,'23/04/2010',11,'Renaud MIGNE');
INSERT INTO MANAGER (MANAGER_ID, PROFILE_ID, LAST_NAME, FIRST_NAME, EMAIL, PHONE, EMPLOYMENT_DATE, EXPERIENCE, BUSINESS_ENGINEER) 
VALUES (3,1,'BONVOISIN','Sébastien','s.bonvoisin@novediagroup.com',102030405,'23/04/2010',8,'Deborah ATTIAS');
INSERT INTO MANAGER (MANAGER_ID, PROFILE_ID, LAST_NAME, FIRST_NAME, EMAIL, PHONE, EMPLOYMENT_DATE, EXPERIENCE, BUSINESS_ENGINEER) 
VALUES (4,4,'BRULATOUT','Eric','e.brulatout@novediagroup.com',102030405,'23/04/2010',9,'Renaud MIGNE');
INSERT INTO MANAGER (MANAGER_ID, PROFILE_ID, LAST_NAME, FIRST_NAME, EMAIL, PHONE, EMPLOYMENT_DATE, EXPERIENCE, BUSINESS_ENGINEER) 
VALUES (5,1,'ACKERMANN','Bruno','b.ackermann@novediagroup.com',102030405,'23/04/2010',12,'Renaud MIGNE');
INSERT INTO MANAGER (MANAGER_ID, PROFILE_ID, LAST_NAME, FIRST_NAME, EMAIL, PHONE, EMPLOYMENT_DATE, EXPERIENCE, BUSINESS_ENGINEER) 
VALUES (6,6,'DANTO','Fanny','f.danto@novedia-solutions.com',102030405,'23/04/2010',5,'Julie VIGNERON');
INSERT INTO MANAGER (MANAGER_ID, PROFILE_ID, LAST_NAME, FIRST_NAME, EMAIL, PHONE, EMPLOYMENT_DATE, EXPERIENCE, BUSINESS_ENGINEER) 
VALUES (7,1,'DEJONGHE','Xavier','x.dejonghe@novedia-solutions.com',102030405,'23/04/2010',6,'Julie VIGNERON');
COMMIT;

-----------------------
-- SEQUENCE UPDATE  --
-----------------------
DROP SEQUENCE SEQMANAGER;
CREATE SEQUENCE SEQMANAGER MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 8 NOCACHE;

COMMIT;

