---------------------------
--    DATA INSERTION     --
---------------------------
INSERT INTO AUTHENTIFICATION (AUTHENTIFICATION_ID, COLLAB_ID, LOGIN, PASSWORD)
VALUES (1,35,'v.dibi','v.dibi');
INSERT INTO AUTHENTIFICATION (AUTHENTIFICATION_ID, COLLAB_ID, LOGIN, PASSWORD)
VALUES (2,2,'e.moumbe','e.moumbe');
INSERT INTO AUTHENTIFICATION (AUTHENTIFICATION_ID, COLLAB_ID, LOGIN, PASSWORD)
VALUES (3,3,'v.guillemain','v.guillemain');
INSERT INTO AUTHENTIFICATION (AUTHENTIFICATION_ID, COLLAB_ID, LOGIN, PASSWORD)
VALUES (4,36,'j.ms','j.ms');
COMMIT;
