---------------------------
--    DATA INSERTION     --
---------------------------
INSERT INTO COLLABORATOR (COLLAB_ID, MANAGER_ID, PROFILE_ID, LAST_NAME, FIRST_NAME, EMAIL, PHONE, EMPLOYMENT_DATE, EXPERIENCE, BUSINESS_ENGINEER) 
VALUES (1,1,5,'COLLET','Julien','j.collet@novedia-solution.com',102030405,'23/04/2010',1,'Renaud MIGNE');
INSERT INTO COLLABORATOR (COLLAB_ID, MANAGER_ID, PROFILE_ID, LAST_NAME, FIRST_NAME, EMAIL, PHONE, EMPLOYMENT_DATE, EXPERIENCE, BUSINESS_ENGINEER) 
VALUES (2,1,1,'MOUMBE','Elisé','e.moumbe@novedia-solution.com',102030415,'23/04/2010',2,'Julie VIGNERON');
INSERT INTO COLLABORATOR (COLLAB_ID, MANAGER_ID, PROFILE_ID, LAST_NAME, FIRST_NAME, EMAIL, PHONE, EMPLOYMENT_DATE, EXPERIENCE, BUSINESS_ENGINEER) 
VALUES (3,3,4,'GUILLEMAIN','Vanessa','v.guillemain@novedia-solution.com',102030425,'23/04/2010',3,'Déborah ATTIAS');
INSERT INTO COLLABORATOR (COLLAB_ID, MANAGER_ID, PROFILE_ID, LAST_NAME, FIRST_NAME, EMAIL, PHONE, EMPLOYMENT_DATE, EXPERIENCE, BUSINESS_ENGINEER) 
VALUES (4,3,5,'CHAUVIE','Olivier','o.chauvie@novedia-solution.com',102030435,'23/04/2010',8,'Renaud MIGNE');
INSERT INTO COLLABORATOR (COLLAB_ID, MANAGER_ID, PROFILE_ID, LAST_NAME, FIRST_NAME, EMAIL, PHONE, EMPLOYMENT_DATE, EXPERIENCE, BUSINESS_ENGINEER) 
VALUES (5,4,5,'BRULATOUT','Eric','e.brulatout@novedia-solution.com',102030445,'23/04/2010',7,'Julie VIGNERON');
INSERT INTO COLLABORATOR (COLLAB_ID, MANAGER_ID, PROFILE_ID, LAST_NAME, FIRST_NAME, EMAIL, PHONE, EMPLOYMENT_DATE, EXPERIENCE, BUSINESS_ENGINEER) 
VALUES (6,2,1,'CAUMARTIN','Régine','r.caumartin@novedia-solution.com',102030455,'23/04/2010',6,'Déborah ATTIAS');
INSERT INTO COLLABORATOR (COLLAB_ID, MANAGER_ID, PROFILE_ID, LAST_NAME, FIRST_NAME, EMAIL, PHONE, EMPLOYMENT_DATE, EXPERIENCE, BUSINESS_ENGINEER) 
VALUES (7,2,5,'ANGLADE','Mathias','m.anglade@novedia-solution.com',102030465,'23/04/2010',2,'Renaud MIGNE');
INSERT INTO COLLABORATOR (COLLAB_ID, MANAGER_ID, PROFILE_ID, LAST_NAME, FIRST_NAME, EMAIL, PHONE, EMPLOYMENT_DATE, EXPERIENCE, BUSINESS_ENGINEER) 
VALUES (8,2,6,'THAI','Shien-Haur','s.thai@novedia-solution.com',102030475,'23/04/2010',4,'Julie VIGNERON');
INSERT INTO COLLABORATOR (COLLAB_ID, MANAGER_ID, PROFILE_ID, LAST_NAME, FIRST_NAME, EMAIL, PHONE, EMPLOYMENT_DATE, EXPERIENCE, BUSINESS_ENGINEER) 
VALUES (9,4,5,'EYCHENNE','Patrick','p.eychenne@novedia-solution.com',102030485,'23/04/2010',6,'Déborah ATTIAS');
INSERT INTO COLLABORATOR (COLLAB_ID, MANAGER_ID, PROFILE_ID, LAST_NAME, FIRST_NAME, EMAIL, PHONE, EMPLOYMENT_DATE, EXPERIENCE, BUSINESS_ENGINEER) 
VALUES (10,5,6,'ROBIN','Murielle','m.robin@novedia-solution.com',102030495,'23/04/2010',5,'Renaud MIGNE');
INSERT INTO COLLABORATOR (COLLAB_ID, MANAGER_ID, PROFILE_ID, LAST_NAME, FIRST_NAME, EMAIL, PHONE, EMPLOYMENT_DATE, EXPERIENCE, BUSINESS_ENGINEER) 
VALUES (11,5,3,'RAVINE','Sandrine','s.ravine@novedia-solution.com',102030505,'23/04/2010',7,'Julie VIGNERON');
INSERT INTO COLLABORATOR (COLLAB_ID, MANAGER_ID, PROFILE_ID, LAST_NAME, FIRST_NAME, EMAIL, PHONE, EMPLOYMENT_DATE, EXPERIENCE, BUSINESS_ENGINEER) 
VALUES (12,6,6,'LOET','Sylvie','s.loet@novedia-solution.com',102030515,'23/04/2010',9,'Renaud MIGNE');
INSERT INTO COLLABORATOR (COLLAB_ID, MANAGER_ID, PROFILE_ID, LAST_NAME, FIRST_NAME, EMAIL, PHONE, EMPLOYMENT_DATE, EXPERIENCE, BUSINESS_ENGINEER) 
VALUES (13,1,1,'BERTON','Alexandre ','a.berton@novedia-solutions.com',102030525,'23/04/2010',1,'Renaud MIGNE');
INSERT INTO COLLABORATOR (COLLAB_ID, MANAGER_ID, PROFILE_ID, LAST_NAME, FIRST_NAME, EMAIL, PHONE, EMPLOYMENT_DATE, EXPERIENCE, BUSINESS_ENGINEER) 
VALUES (14,1,4,'BOUDICH','Karim','k.boudich@novedia-solutions.com',102030535,'23/04/2010',2,'Julie VIGNERON');
INSERT INTO COLLABORATOR (COLLAB_ID, MANAGER_ID, PROFILE_ID, LAST_NAME, FIRST_NAME, EMAIL, PHONE, EMPLOYMENT_DATE, EXPERIENCE, BUSINESS_ENGINEER) 
VALUES (15,3,2,'CHEVALIER','Isabelle','i.chevalier@novedia-solutions.com',102030545,'23/04/2010',3,'Déborah ATTIAS');
INSERT INTO COLLABORATOR (COLLAB_ID, MANAGER_ID, PROFILE_ID, LAST_NAME, FIRST_NAME, EMAIL, PHONE, EMPLOYMENT_DATE, EXPERIENCE, BUSINESS_ENGINEER) 
VALUES (16,5,4,'GALOT','Anne-lise','al.galot@novedia-solutions.com',102030555,'23/04/2010',8,'Renaud MIGNE');
INSERT INTO COLLABORATOR (COLLAB_ID, MANAGER_ID, PROFILE_ID, LAST_NAME, FIRST_NAME, EMAIL, PHONE, EMPLOYMENT_DATE, EXPERIENCE, BUSINESS_ENGINEER) 
VALUES (17,4,2,'FAUQUEMBERGUE','Eric','e.fauquembergue@novedia-solutions.com',102030565,'23/04/2010',7,'Julie VIGNERON');
INSERT INTO COLLABORATOR (COLLAB_ID, MANAGER_ID, PROFILE_ID, LAST_NAME, FIRST_NAME, EMAIL, PHONE, EMPLOYMENT_DATE, EXPERIENCE, BUSINESS_ENGINEER) 
VALUES (18,1,6,'GERMOND','Sébastien','s.germond@novedia-solutions.com',102030575,'23/04/2010',6,'Déborah ATTIAS');
INSERT INTO COLLABORATOR (COLLAB_ID, MANAGER_ID, PROFILE_ID, LAST_NAME, FIRST_NAME, EMAIL, PHONE, EMPLOYMENT_DATE, EXPERIENCE, BUSINESS_ENGINEER) 
VALUES (19,7,6,'GRELIER','Vincent','v.grelier@novedia-solutions.com',102030585,'23/04/2010',2,'Julie VIGNERON');
INSERT INTO COLLABORATOR (COLLAB_ID, MANAGER_ID, PROFILE_ID, LAST_NAME, FIRST_NAME, EMAIL, PHONE, EMPLOYMENT_DATE, EXPERIENCE, BUSINESS_ENGINEER) 
VALUES (20,3,1,'LE GUENNEC','Julien','j.leguennec@novedia-solutions.com',102030595,'23/04/2010',4,'Déborah ATTIAS');
INSERT INTO COLLABORATOR (COLLAB_ID, MANAGER_ID, PROFILE_ID, LAST_NAME, FIRST_NAME, EMAIL, PHONE, EMPLOYMENT_DATE, EXPERIENCE, BUSINESS_ENGINEER) 
VALUES (21,4,3,'ANDRIET','Louis','l.andriet@novedia-solutions.com',102030605,'23/04/2010',6,'Renaud MIGNE');
INSERT INTO COLLABORATOR (COLLAB_ID, MANAGER_ID, PROFILE_ID, LAST_NAME, FIRST_NAME, EMAIL, PHONE, EMPLOYMENT_DATE, EXPERIENCE, BUSINESS_ENGINEER) 
VALUES (22,3,5,'AVRIL','Thierry','t.avril@novedia-solutions.com',102030615,'23/04/2010',5,'Julie VIGNERON');
INSERT INTO COLLABORATOR (COLLAB_ID, MANAGER_ID, PROFILE_ID, LAST_NAME, FIRST_NAME, EMAIL, PHONE, EMPLOYMENT_DATE, EXPERIENCE, BUSINESS_ENGINEER) 
VALUES (23,1,1,'BONNEAU','Johan','j.bonneau@novedia-solutions.com',102030625,'23/04/2010',7,'Déborah ATTIAS');
INSERT INTO COLLABORATOR (COLLAB_ID, MANAGER_ID, PROFILE_ID, LAST_NAME, FIRST_NAME, EMAIL, PHONE, EMPLOYMENT_DATE, EXPERIENCE, BUSINESS_ENGINEER) 
VALUES (24,7,3,'BALFIN','Guillaume','g.balfin@novedia-agency.com',102030635,'23/04/2010',9,'Renaud MIGNE');
INSERT INTO COLLABORATOR (COLLAB_ID, MANAGER_ID, PROFILE_ID, LAST_NAME, FIRST_NAME, EMAIL, PHONE, EMPLOYMENT_DATE, EXPERIENCE, BUSINESS_ENGINEER) 
VALUES (25,3,2,'BOUADJIE','Paule','p.bouadjie@novedia-solutions.com',102030645,'23/04/2010',1,'Julie VIGNERON');
INSERT INTO COLLABORATOR (COLLAB_ID, MANAGER_ID, PROFILE_ID, LAST_NAME, FIRST_NAME, EMAIL, PHONE, EMPLOYMENT_DATE, EXPERIENCE, BUSINESS_ENGINEER) 
VALUES (26,4,6,'BELMQADEM','Houda','h.belmqadem@novedia-decision.com',102030655,'23/04/2010',2,'Renaud MIGNE');
INSERT INTO COLLABORATOR (COLLAB_ID, MANAGER_ID, PROFILE_ID, LAST_NAME, FIRST_NAME, EMAIL, PHONE, EMPLOYMENT_DATE, EXPERIENCE, BUSINESS_ENGINEER) 
VALUES (27,7,5,'HENRY','Mickaël','m.henry@novedia-solutions.com',102030665,'23/04/2010',3,'Renaud MIGNE');
INSERT INTO COLLABORATOR (COLLAB_ID, MANAGER_ID, PROFILE_ID, LAST_NAME, FIRST_NAME, EMAIL, PHONE, EMPLOYMENT_DATE, EXPERIENCE, BUSINESS_ENGINEER) 
VALUES (28,3,4,'DEROUICH','Amina','a.derouich@novedia-decision.com',102030675,'23/04/2010',8,'Julie VIGNERON');
INSERT INTO COLLABORATOR (COLLAB_ID, MANAGER_ID, PROFILE_ID, LAST_NAME, FIRST_NAME, EMAIL, PHONE, EMPLOYMENT_DATE, EXPERIENCE, BUSINESS_ENGINEER) 
VALUES (29,5,1,'DREUX','Hélène','h.dreux@novedia-solutions.com',102030685,'23/04/2010',7,'Déborah ATTIAS');
INSERT INTO COLLABORATOR (COLLAB_ID, MANAGER_ID, PROFILE_ID, LAST_NAME, FIRST_NAME, EMAIL, PHONE, EMPLOYMENT_DATE, EXPERIENCE, BUSINESS_ENGINEER) 
VALUES (30,6,2,'ALLIX','Erwan','e.allix@novedia-solutions.com',102030695,'23/04/2010',6,'Renaud MIGNE');
INSERT INTO COLLABORATOR (COLLAB_ID, MANAGER_ID, PROFILE_ID, LAST_NAME, FIRST_NAME, EMAIL, PHONE, EMPLOYMENT_DATE, EXPERIENCE, BUSINESS_ENGINEER) 
VALUES (31,2,1,'HUBERT','Jean-lou','j.hubert@novedia-solutions.com',102030705,'23/04/2010',2,'Julie VIGNERON');
INSERT INTO COLLABORATOR (COLLAB_ID, MANAGER_ID, PROFILE_ID, LAST_NAME, FIRST_NAME, EMAIL, PHONE, EMPLOYMENT_DATE, EXPERIENCE, BUSINESS_ENGINEER) 
VALUES (32,2,6,'PELLOT','Stéphane','s.pellot@novedia-solutions.com',102030715,'23/04/2010',4,'Renaud MIGNE');
INSERT INTO COLLABORATOR (COLLAB_ID, MANAGER_ID, PROFILE_ID, LAST_NAME, FIRST_NAME, EMAIL, PHONE, EMPLOYMENT_DATE, EXPERIENCE, BUSINESS_ENGINEER) 
VALUES (33,5,4,'MERLET','Sylvain','s.merlet@novedia-solutions.com',102030725,'23/04/2010',6,'Renaud MIGNE');
INSERT INTO COLLABORATOR (COLLAB_ID, MANAGER_ID, PROFILE_ID, LAST_NAME, FIRST_NAME, EMAIL, PHONE, EMPLOYMENT_DATE, EXPERIENCE, BUSINESS_ENGINEER) 
VALUES (34,6,1,'MAESTRACCI','Mirana','m.maestracci@novedia-solutions.com',102030735,'23/04/2010',5,'Julie VIGNERON');
COMMIT;
