---------------------------
--    DATA INSERTION     --
---------------------------
INSERT INTO CONCEPT (CONCEPT_ID, CATEGORY_ID, CONCEPT_NAME)
VALUES (1,1,'IOC');
INSERT INTO CONCEPT (CONCEPT_ID, CATEGORY_ID, CONCEPT_NAME)
VALUES (2,1,'ORM');
INSERT INTO CONCEPT (CONCEPT_ID, CATEGORY_ID, CONCEPT_NAME)
VALUES (3,2,'IOC');
INSERT INTO CONCEPT (CONCEPT_ID, CATEGORY_ID, CONCEPT_NAME)
VALUES (4,2,'ORM');
INSERT INTO CONCEPT (CONCEPT_ID, CATEGORY_ID, CONCEPT_NAME)
VALUES (5,3,'ORM');
INSERT INTO CONCEPT (CONCEPT_ID, CATEGORY_ID, CONCEPT_NAME)
VALUES (6,3,'IOC');
INSERT INTO CONCEPT (CONCEPT_ID, CATEGORY_ID, CONCEPT_NAME)
VALUES (7,4,'IOC');
INSERT INTO CONCEPT (CONCEPT_ID, CATEGORY_ID, CONCEPT_NAME)
VALUES (8,4,'ORM');
INSERT INTO CONCEPT (CONCEPT_ID, CATEGORY_ID, CONCEPT_NAME)
VALUES (9,5,'SGBD');
INSERT INTO CONCEPT (CONCEPT_ID, CATEGORY_ID, CONCEPT_NAME)
VALUES (10,1,'Tests Unitaires');
INSERT INTO CONCEPT (CONCEPT_ID, CATEGORY_ID, CONCEPT_NAME)
VALUES (11,2,'Tests Unitaires');
INSERT INTO CONCEPT (CONCEPT_ID, CATEGORY_ID, CONCEPT_NAME)
VALUES (12,6,'Conception');
INSERT INTO CONCEPT (CONCEPT_ID, CATEGORY_ID, CONCEPT_NAME)
VALUES (13,7,'Qualité');
INSERT INTO CONCEPT (CONCEPT_ID, CATEGORY_ID, CONCEPT_NAME)
VALUES (14,8,'Suivi');
INSERT INTO CONCEPT (CONCEPT_ID, CATEGORY_ID, CONCEPT_NAME)
VALUES (15,8,'Gestion');
INSERT INTO CONCEPT (CONCEPT_ID, CATEGORY_ID, CONCEPT_NAME)
VALUES (16,9,'Suivi');
INSERT INTO CONCEPT (CONCEPT_ID, CATEGORY_ID, CONCEPT_NAME)
VALUES (17,9,'Gestion');
COMMIT;

-----------------------
-- SEQUENCE UPDATE --
-----------------------
DROP SEQUENCE SEQCONCEPT;
CREATE SEQUENCE SEQCONCEPT MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 18 NOCACHE;

COMMIT;