---------------------------
--    DATA INSERTION     --
---------------------------
INSERT INTO SKILL (COLLEAGUE_ID, TOOL_ID, USE_FREQUENCY, NO_USING_TIME, SCORE)
VALUES (2,1,3,1,5);
INSERT INTO SKILL (COLLEAGUE_ID, TOOL_ID, USE_FREQUENCY, NO_USING_TIME, SCORE)
VALUES (2,2,3,3,5);
INSERT INTO SKILL (COLLEAGUE_ID, TOOL_ID, USE_FREQUENCY, NO_USING_TIME, SCORE)
VALUES (2,3,1,2,4);
INSERT INTO SKILL (COLLEAGUE_ID, TOOL_ID, USE_FREQUENCY, NO_USING_TIME, SCORE)
VALUES (2,3,1,2,4);
INSERT INTO SKILL (COLLEAGUE_ID, TOOL_ID, USE_FREQUENCY, NO_USING_TIME, SCORE)
VALUES (2,4,3,2,4);
INSERT INTO SKILL (COLLEAGUE_ID, TOOL_ID, USE_FREQUENCY, NO_USING_TIME, SCORE)
VALUES (2,5,3,3,5);
INSERT INTO SKILL (COLLEAGUE_ID, TOOL_ID, USE_FREQUENCY, NO_USING_TIME, SCORE)
VALUES (2,6,1,3,3);
INSERT INTO SKILL (COLLEAGUE_ID, TOOL_ID, USE_FREQUENCY, NO_USING_TIME, SCORE)
VALUES (2,7,3,3,5);
INSERT INTO SKILL (COLLEAGUE_ID, TOOL_ID, USE_FREQUENCY, NO_USING_TIME, SCORE)
VALUES (2,12,1,2,5);
INSERT INTO SKILL (COLLEAGUE_ID, TOOL_ID, USE_FREQUENCY, NO_USING_TIME, SCORE)
VALUES (2,13,1,2,4);
INSERT INTO SKILL (COLLEAGUE_ID, TOOL_ID, USE_FREQUENCY, NO_USING_TIME, SCORE)
VALUES (2,13,1,2,4);
INSERT INTO SKILL (COLLEAGUE_ID, TOOL_ID, USE_FREQUENCY, NO_USING_TIME, SCORE)
VALUES (2,13,1,2,4);
INSERT INTO SKILL (COLLEAGUE_ID, TOOL_ID, USE_FREQUENCY, NO_USING_TIME, SCORE)
VALUES (2,14,1,1,3);
INSERT INTO SKILL (COLLEAGUE_ID, TOOL_ID, USE_FREQUENCY, NO_USING_TIME, SCORE)
VALUES (2,15,1,5,2);
INSERT INTO SKILL (COLLEAGUE_ID, TOOL_ID, USE_FREQUENCY, NO_USING_TIME, SCORE)
VALUES (2,17,3,4,4);
INSERT INTO SKILL (COLLEAGUE_ID, TOOL_ID, USE_FREQUENCY, NO_USING_TIME, SCORE)
VALUES (2,20,3,3,5);
INSERT INTO SKILL (COLLEAGUE_ID, TOOL_ID, USE_FREQUENCY, NO_USING_TIME, SCORE)
VALUES (2,30,3,3,5);
INSERT INTO SKILL (COLLEAGUE_ID, TOOL_ID, USE_FREQUENCY, NO_USING_TIME, SCORE)
VALUES (2,35,3,3,4);
INSERT INTO SKILL (COLLEAGUE_ID, TOOL_ID, USE_FREQUENCY, NO_USING_TIME, SCORE)
VALUES (2,37,3,2,3);
INSERT INTO SKILL (COLLEAGUE_ID, TOOL_ID, USE_FREQUENCY, NO_USING_TIME, SCORE)
VALUES (2,38,1,1,4);
INSERT INTO SKILL (COLLEAGUE_ID, TOOL_ID, USE_FREQUENCY, NO_USING_TIME, SCORE)
VALUES (2,50,2,2,4);
COMMIT;


