---------------------------
--    DATA INSERTION     --
---------------------------
INSERT INTO SKILL (COLLAB_ID, TOOL_ID, USE_FREQUENCY, NO_USING_TIME, SCORE)
VALUES (11,22,2,5,1);
INSERT INTO SKILL (COLLAB_ID, TOOL_ID, USE_FREQUENCY, NO_USING_TIME, SCORE)
VALUES (14,42,3,1,3);
INSERT INTO SKILL (COLLAB_ID, TOOL_ID, USE_FREQUENCY, NO_USING_TIME, SCORE)
VALUES (14,53,2,5,4);
INSERT INTO SKILL (COLLAB_ID, TOOL_ID, USE_FREQUENCY, NO_USING_TIME, SCORE)
VALUES (8,37,3,2,5);
INSERT INTO SKILL (COLLAB_ID, TOOL_ID, USE_FREQUENCY, NO_USING_TIME, SCORE)
VALUES (13,57,1,5,4);
INSERT INTO SKILL (COLLAB_ID, TOOL_ID, USE_FREQUENCY, NO_USING_TIME, SCORE)
VALUES (14,62,2,3,2);
INSERT INTO SKILL (COLLAB_ID, TOOL_ID, USE_FREQUENCY, NO_USING_TIME, SCORE)
VALUES (10,45,2,4,5);
INSERT INTO SKILL (COLLAB_ID, TOOL_ID, USE_FREQUENCY, NO_USING_TIME, SCORE)
VALUES (20,18,1,3,1);
INSERT INTO SKILL (COLLAB_ID, TOOL_ID, USE_FREQUENCY, NO_USING_TIME, SCORE)
VALUES (29,26,1,3,3);
INSERT INTO SKILL (COLLAB_ID, TOOL_ID, USE_FREQUENCY, NO_USING_TIME, SCORE)
VALUES (32,3,2,2,4);
INSERT INTO SKILL (COLLAB_ID, TOOL_ID, USE_FREQUENCY, NO_USING_TIME, SCORE)
VALUES (20,42,2,1,4);
INSERT INTO SKILL (COLLAB_ID, TOOL_ID, USE_FREQUENCY, NO_USING_TIME, SCORE)
VALUES (2,46,3,1,1);
INSERT INTO SKILL (COLLAB_ID, TOOL_ID, USE_FREQUENCY, NO_USING_TIME, SCORE)
VALUES (2,5,3,5,3);
INSERT INTO SKILL (COLLAB_ID, TOOL_ID, USE_FREQUENCY, NO_USING_TIME, SCORE)
VALUES (19,20,3,3,3);
INSERT INTO SKILL (COLLAB_ID, TOOL_ID, USE_FREQUENCY, NO_USING_TIME, SCORE)
VALUES (23,20,3,2,5);
INSERT INTO SKILL (COLLAB_ID, TOOL_ID, USE_FREQUENCY, NO_USING_TIME, SCORE)
VALUES (7,21,2,2,2);
INSERT INTO SKILL (COLLAB_ID, TOOL_ID, USE_FREQUENCY, NO_USING_TIME, SCORE)
VALUES (28,56,2,5,4);
INSERT INTO SKILL (COLLAB_ID, TOOL_ID, USE_FREQUENCY, NO_USING_TIME, SCORE)
VALUES (2,5,1,3,2);
INSERT INTO SKILL (COLLAB_ID, TOOL_ID, USE_FREQUENCY, NO_USING_TIME, SCORE)
VALUES (16,41,1,2,4);
INSERT INTO SKILL (COLLAB_ID, TOOL_ID, USE_FREQUENCY, NO_USING_TIME, SCORE)
VALUES (2,32,1,4,2);
INSERT INTO SKILL (COLLAB_ID, TOOL_ID, USE_FREQUENCY, NO_USING_TIME, SCORE)
VALUES (3,25,1,3,4);
INSERT INTO SKILL (COLLAB_ID, TOOL_ID, USE_FREQUENCY, NO_USING_TIME, SCORE)
VALUES (32,1,2,5,5);
INSERT INTO SKILL (COLLAB_ID, TOOL_ID, USE_FREQUENCY, NO_USING_TIME, SCORE)
VALUES (7,48,1,2,2);
INSERT INTO SKILL (COLLAB_ID, TOOL_ID, USE_FREQUENCY, NO_USING_TIME, SCORE)
VALUES (3,37,1,1,1);
INSERT INTO SKILL (COLLAB_ID, TOOL_ID, USE_FREQUENCY, NO_USING_TIME, SCORE)
VALUES (3,34,3,2,5);
INSERT INTO SKILL (COLLAB_ID, TOOL_ID, USE_FREQUENCY, NO_USING_TIME, SCORE)
VALUES (28,58,3,4,2);
INSERT INTO SKILL (COLLAB_ID, TOOL_ID, USE_FREQUENCY, NO_USING_TIME, SCORE)
VALUES (28,38,2,4,3);
INSERT INTO SKILL (COLLAB_ID, TOOL_ID, USE_FREQUENCY, NO_USING_TIME, SCORE)
VALUES (12,27,3,4,3);
INSERT INTO SKILL (COLLAB_ID, TOOL_ID, USE_FREQUENCY, NO_USING_TIME, SCORE)
VALUES (11,47,2,1,3);
INSERT INTO SKILL (COLLAB_ID, TOOL_ID, USE_FREQUENCY, NO_USING_TIME, SCORE)
VALUES (3,35,3,4,3);
INSERT INTO SKILL (COLLAB_ID, TOOL_ID, USE_FREQUENCY, NO_USING_TIME, SCORE)
VALUES (19,21,2,4,5);
INSERT INTO SKILL (COLLAB_ID, TOOL_ID, USE_FREQUENCY, NO_USING_TIME, SCORE)
VALUES (27,35,2,4,4);
INSERT INTO SKILL (COLLAB_ID, TOOL_ID, USE_FREQUENCY, NO_USING_TIME, SCORE)
VALUES (17,12,3,4,4);
INSERT INTO SKILL (COLLAB_ID, TOOL_ID, USE_FREQUENCY, NO_USING_TIME, SCORE)
VALUES (17,10,3,2,2);
INSERT INTO SKILL (COLLAB_ID, TOOL_ID, USE_FREQUENCY, NO_USING_TIME, SCORE)
VALUES (10,26,2,2,5);
INSERT INTO SKILL (COLLAB_ID, TOOL_ID, USE_FREQUENCY, NO_USING_TIME, SCORE)
VALUES (20,18,2,5,3);
INSERT INTO SKILL (COLLAB_ID, TOOL_ID, USE_FREQUENCY, NO_USING_TIME, SCORE)
VALUES (5,21,2,1,4);
INSERT INTO SKILL (COLLAB_ID, TOOL_ID, USE_FREQUENCY, NO_USING_TIME, SCORE)
VALUES (10,48,1,5,3);
INSERT INTO SKILL (COLLAB_ID, TOOL_ID, USE_FREQUENCY, NO_USING_TIME, SCORE)
VALUES (24,46,3,4,5);
INSERT INTO SKILL (COLLAB_ID, TOOL_ID, USE_FREQUENCY, NO_USING_TIME, SCORE)
VALUES (7,34,2,1,5);
INSERT INTO SKILL (COLLAB_ID, TOOL_ID, USE_FREQUENCY, NO_USING_TIME, SCORE)
VALUES (28,40,3,2,2);
INSERT INTO SKILL (COLLAB_ID, TOOL_ID, USE_FREQUENCY, NO_USING_TIME, SCORE)
VALUES (32,9,3,3,2);
INSERT INTO SKILL (COLLAB_ID, TOOL_ID, USE_FREQUENCY, NO_USING_TIME, SCORE)
VALUES (10,40,2,4,3);
INSERT INTO SKILL (COLLAB_ID, TOOL_ID, USE_FREQUENCY, NO_USING_TIME, SCORE)
VALUES (9,50,2,2,5);
INSERT INTO SKILL (COLLAB_ID, TOOL_ID, USE_FREQUENCY, NO_USING_TIME, SCORE)
VALUES (6,4,2,2,1);
INSERT INTO SKILL (COLLAB_ID, TOOL_ID, USE_FREQUENCY, NO_USING_TIME, SCORE)
VALUES (12,20,1,5,1);
INSERT INTO SKILL (COLLAB_ID, TOOL_ID, USE_FREQUENCY, NO_USING_TIME, SCORE)
VALUES (33,59,2,1,5);
COMMIT;
