---------------------------
--    DATA INSERTION     --
---------------------------
INSERT INTO PROFILE (PROFILE_ID, PROFILE_TYPE)
VALUES (1,'Développeur');
INSERT INTO PROFILE (PROFILE_ID, PROFILE_TYPE)
VALUES (2,'Fonctionnel');
INSERT INTO PROFILE (PROFILE_ID, PROFILE_TYPE)
VALUES (3,'Chef de Projet');
INSERT INTO PROFILE (PROFILE_ID, PROFILE_TYPE)
VALUES (4,'Architecte Technique');
INSERT INTO PROFILE (PROFILE_ID, PROFILE_TYPE)
VALUES (5,'Architecte Fonct.');
INSERT INTO PROFILE (PROFILE_ID, PROFILE_TYPE)
VALUES (6,'Testeur');
COMMIT;
