---------------------------
--    DATA INSERTION     --
---------------------------
INSERT INTO MISSION (MISSION_ID, COLLEAGUE_ID, TITLE, PLACE, CLIENT_ID, NOTES, START_DATE, END_DATE)
VALUES (1,20,'Moteur de recherche','Lille',1,'','26/2/2008','24/12/2012');
INSERT INTO MISSION (MISSION_ID, COLLEAGUE_ID, TITLE, PLACE, CLIENT_ID, NOTES, START_DATE, END_DATE)
VALUES (2,17,'Publications','Grenoble',1,'','11/1/2005','1/1/2012');
INSERT INTO MISSION (MISSION_ID, COLLEAGUE_ID, TITLE, PLACE, CLIENT_ID, NOTES, START_DATE, END_DATE)
VALUES (3,1,'Statistiques de pannes','New-York',2,'','26/5/2006','13/5/2012');
INSERT INTO MISSION (MISSION_ID, COLLEAGUE_ID, TITLE, PLACE, CLIENT_ID, NOTES, START_DATE, END_DATE)
VALUES (4,13,'Moteur de recherche','Boulogne',3,'','25/4/2004','17/11/2009');
INSERT INTO MISSION (MISSION_ID, COLLEAGUE_ID, TITLE, PLACE, CLIENT_ID, NOTES, START_DATE, END_DATE)
VALUES (5,17,'Site intranet','San Francisco',1,'','2/6/2003','8/7/2010');
INSERT INTO MISSION (MISSION_ID, COLLEAGUE_ID, TITLE, PLACE, CLIENT_ID, NOTES, START_DATE, END_DATE)
VALUES (6,6,'Recherche Et Developpement','Londres',4,'','10/11/2009','16/10/2012');
INSERT INTO MISSION (MISSION_ID, COLLEAGUE_ID, TITLE, PLACE, CLIENT_ID, NOTES, START_DATE, END_DATE)
VALUES (7,19,'Moteur de recherche','Paris',5,'','23/10/2004','26/5/2011');
INSERT INTO MISSION (MISSION_ID, COLLEAGUE_ID, TITLE, PLACE, CLIENT_ID, NOTES, START_DATE, END_DATE)
VALUES (8,26,'Gestion des forces de vente','Grenoble',1,'','3/2/2005','26/5/2011');
INSERT INTO MISSION (MISSION_ID, COLLEAGUE_ID, TITLE, PLACE, CLIENT_ID, NOTES, START_DATE, END_DATE)
VALUES (9,25,'Site intranet','Belgique',4,'','8/11/2003','8/9/2010');
INSERT INTO MISSION (MISSION_ID, COLLEAGUE_ID, TITLE, PLACE, CLIENT_ID, NOTES, START_DATE, END_DATE)
VALUES (10,33,'Statistiques de pannes','Belgique',2,'','19/6/1999','2/10/2009');
INSERT INTO MISSION (MISSION_ID, COLLEAGUE_ID, TITLE, PLACE, CLIENT_ID, NOTES, START_DATE, END_DATE)
VALUES (11,28,'Statistiques de ventes','San Francisco',6,'','5/12/2003','21/12/2009');
INSERT INTO MISSION (MISSION_ID, COLLEAGUE_ID, TITLE, PLACE, CLIENT_ID, NOTES, START_DATE, END_DATE)
VALUES (12,6,'Base de collecte de votes','Grenoble',2,'','8/7/2003','4/2/2011');
INSERT INTO MISSION (MISSION_ID, COLLEAGUE_ID, TITLE, PLACE, CLIENT_ID, NOTES, START_DATE, END_DATE)
VALUES (13,28,'Gestion des forces de vente','Londres',7,'','26/11/2002','3/5/2009');
INSERT INTO MISSION (MISSION_ID, COLLEAGUE_ID, TITLE, PLACE, CLIENT_ID, NOTES, START_DATE, END_DATE)
VALUES (14,32,'Site intranet','Nice',8,'','13/12/1999','4/4/2009');
INSERT INTO MISSION (MISSION_ID, COLLEAGUE_ID, TITLE, PLACE, CLIENT_ID, NOTES, START_DATE, END_DATE)
VALUES (15,10,'Application embarquée','Saint-Denis',9,'','21/9/1998','15/2/2012');
INSERT INTO MISSION (MISSION_ID, COLLEAGUE_ID, TITLE, PLACE, CLIENT_ID, NOTES, START_DATE, END_DATE)
VALUES (16,34,'Statistiques de pannes','Marseille',3,'','11/1/2003','12/7/2011');
INSERT INTO MISSION (MISSION_ID, COLLEAGUE_ID, TITLE, PLACE, CLIENT_ID, NOTES, START_DATE, END_DATE)
VALUES (17,5,'Gestion des forces de vente','Londres',10,'','17/8/2003','11/9/2010');
INSERT INTO MISSION (MISSION_ID, COLLEAGUE_ID, TITLE, PLACE, CLIENT_ID, NOTES, START_DATE, END_DATE)
VALUES (18,6,'IHM de paramétrie','Londres',3,'','4/5/2009','7/7/2010');
INSERT INTO MISSION (MISSION_ID, COLLEAGUE_ID, TITLE, PLACE, CLIENT_ID, NOTES, START_DATE, END_DATE)
VALUES (19,15,'Application embarquée','Lyon',9,'','24/6/2008','12/4/2010');
INSERT INTO MISSION (MISSION_ID, COLLEAGUE_ID, TITLE, PLACE, CLIENT_ID, NOTES, START_DATE, END_DATE)
VALUES (20,9,'Site intranet','Lyon',11,'','2/1/2000','24/12/2010');
INSERT INTO MISSION (MISSION_ID, COLLEAGUE_ID, TITLE, PLACE, CLIENT_ID, NOTES, START_DATE, END_DATE)
VALUES (21,7,'Publications','Lyon',10,'','3/5/2001','22/8/2009');
INSERT INTO MISSION (MISSION_ID, COLLEAGUE_ID, TITLE, PLACE, CLIENT_ID, NOTES, START_DATE, END_DATE)
VALUES (22,11,'Publications','San Francisco',6,'','11/11/2003','23/3/2011');
INSERT INTO MISSION (MISSION_ID, COLLEAGUE_ID, TITLE, PLACE, CLIENT_ID, NOTES, START_DATE, END_DATE)
VALUES (23,6,'Site intranet','Toulouse',2,'','3/5/2004','26/9/2011');
INSERT INTO MISSION (MISSION_ID, COLLEAGUE_ID, TITLE, PLACE, CLIENT_ID, NOTES, START_DATE, END_DATE)
VALUES (24,24,'IHM de paramétrie','Boulogne',8,'','1/1/2005','7/12/2010');
INSERT INTO MISSION (MISSION_ID, COLLEAGUE_ID, TITLE, PLACE, CLIENT_ID, NOTES, START_DATE, END_DATE)
VALUES (25,14,'Application embarquée','New-York',2,'','20/9/2002','11/2/2011');
COMMIT;

-----------------------
-- SEQUENCE CREATION --
-----------------------
DROP SEQUENCE SEQMISSION;
CREATE SEQUENCE SEQMISSION MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 26 NOCACHE;

COMMIT;