---------------------------
--    DATA INSERTION     --
---------------------------

INSERT INTO AUTHENTICATION (AUTHENTICATION_ID, COLLAB_ID, LOGIN, PASSWORD) VALUES (1,35,'v.dibi','v.dibi');
INSERT INTO AUTHENTICATION (AUTHENTICATION_ID, COLLAB_ID, LOGIN, PASSWORD) VALUES (1,35,'v.guillemain','v.guillemain');
INSERT INTO AUTHENTICATION (AUTHENTICATION_ID, COLLAB_ID, LOGIN, PASSWORD) VALUES (1,35,'e.moumbe','e.moumbe');
INSERT INTO AUTHENTICATION (AUTHENTICATION_ID, COLLAB_ID, LOGIN, PASSWORD) VALUES (1,35,'j.marie-sainte','j.marie-sainte');
INSERT INTO AUTHENTICATION (AUTHENTICATION_ID, COLLAB_ID, LOGIN, PASSWORD) VALUES (1,35,'y.rohr','y.rohr');

COMMIT;
