---------------------------
--    DATA INSERTION     --
---------------------------
INSERT INTO MISSION (MISSION_ID, COLLAB_ID, NAME, PLACE, CLIENT, NOTES, START_DATE, END_DATE)
VALUES (1,20,'Moteur de recherche','Lille','Orange','','26/2/2008','24/12/2012');
INSERT INTO MISSION (MISSION_ID, COLLAB_ID, NAME, PLACE, CLIENT, NOTES, START_DATE, END_DATE)
VALUES (2,17,'Publications','Grenoble','Orange','','11/1/2005','1/1/2012');
INSERT INTO MISSION (MISSION_ID, COLLAB_ID, NAME, PLACE, CLIENT, NOTES, START_DATE, END_DATE)
VALUES (3,1,'Statistiques de pannes','New-York','Air France','','26/5/2006','13/5/2012');
INSERT INTO MISSION (MISSION_ID, COLLAB_ID, NAME, PLACE, CLIENT, NOTES, START_DATE, END_DATE)
VALUES (4,13,'Moteur de recherche','Boulogne','PSA','','25/4/2004','17/11/2009');
INSERT INTO MISSION (MISSION_ID, COLLAB_ID, NAME, PLACE, CLIENT, NOTES, START_DATE, END_DATE)
VALUES (5,17,'Site intranet','San Francisco','Orange','','2/6/2003','8/7/2010');
INSERT INTO MISSION (MISSION_ID, COLLAB_ID, NAME, PLACE, CLIENT, NOTES, START_DATE, END_DATE)
VALUES (6,6,'Recherche Et Developpement','Londres','Canal+','','10/11/2009','16/10/2012');
INSERT INTO MISSION (MISSION_ID, COLLAB_ID, NAME, PLACE, CLIENT, NOTES, START_DATE, END_DATE)
VALUES (7,19,'Moteur de recherche','Paris','Intent','','23/10/2004','26/5/2011');
INSERT INTO MISSION (MISSION_ID, COLLAB_ID, NAME, PLACE, CLIENT, NOTES, START_DATE, END_DATE)
VALUES (8,26,'Gestion des forces de vente','Grenoble','Orange','','3/2/2005','26/5/2011');
INSERT INTO MISSION (MISSION_ID, COLLAB_ID, NAME, PLACE, CLIENT, NOTES, START_DATE, END_DATE)
VALUES (9,25,'Site intranet','Belgique','Canal+','','8/11/2003','8/9/2010');
INSERT INTO MISSION (MISSION_ID, COLLAB_ID, NAME, PLACE, CLIENT, NOTES, START_DATE, END_DATE)
VALUES (10,33,'Statistiques de pannes','Belgique','Air France','','19/6/1999','2/10/2009');
INSERT INTO MISSION (MISSION_ID, COLLAB_ID, NAME, PLACE, CLIENT, NOTES, START_DATE, END_DATE)
VALUES (11,28,'Statistiques de ventes','San Francisco','Total','','5/12/2003','21/12/2009');
INSERT INTO MISSION (MISSION_ID, COLLAB_ID, NAME, PLACE, CLIENT, NOTES, START_DATE, END_DATE)
VALUES (12,6,'Base de collecte de votes','Grenoble','Air France','','8/7/2003','4/2/2011');
INSERT INTO MISSION (MISSION_ID, COLLAB_ID, NAME, PLACE, CLIENT, NOTES, START_DATE, END_DATE)
VALUES (13,28,'Gestion des forces de vente','Londres','Mattel','','26/11/2002','3/5/2009');
INSERT INTO MISSION (MISSION_ID, COLLAB_ID, NAME, PLACE, CLIENT, NOTES, START_DATE, END_DATE)
VALUES (14,32,'Site intranet','Nice','NavBoard','','13/12/1999','4/4/2009');
INSERT INTO MISSION (MISSION_ID, COLLAB_ID, NAME, PLACE, CLIENT, NOTES, START_DATE, END_DATE)
VALUES (15,10,'Application embarquée','Saint-Denis','Citroen','','21/9/1998','15/2/2012');
INSERT INTO MISSION (MISSION_ID, COLLAB_ID, NAME, PLACE, CLIENT, NOTES, START_DATE, END_DATE)
VALUES (16,34,'Statistiques de pannes','Marseille','PSA','','11/1/2003','12/7/2011');
INSERT INTO MISSION (MISSION_ID, COLLAB_ID, NAME, PLACE, CLIENT, NOTES, START_DATE, END_DATE)
VALUES (17,5,'Gestion des forces de vente','Londres','France Télécom','','17/8/2003','11/9/2010');
INSERT INTO MISSION (MISSION_ID, COLLAB_ID, NAME, PLACE, CLIENT, NOTES, START_DATE, END_DATE)
VALUES (18,6,'IHM de paramétrie','Londres','PSA','','4/5/2009','7/7/2010');
INSERT INTO MISSION (MISSION_ID, COLLAB_ID, NAME, PLACE, CLIENT, NOTES, START_DATE, END_DATE)
VALUES (19,15,'Application embarquée','Lyon','Citroen','','24/6/2008','12/4/2010');
INSERT INTO MISSION (MISSION_ID, COLLAB_ID, NAME, PLACE, CLIENT, NOTES, START_DATE, END_DATE)
VALUES (20,9,'Site intranet','Lyon','Hermès','','2/1/2000','24/12/2010');
INSERT INTO MISSION (MISSION_ID, COLLAB_ID, NAME, PLACE, CLIENT, NOTES, START_DATE, END_DATE)
VALUES (21,7,'Publications','Lyon','France Télécom','','3/5/2001','22/8/2009');
INSERT INTO MISSION (MISSION_ID, COLLAB_ID, NAME, PLACE, CLIENT, NOTES, START_DATE, END_DATE)
VALUES (22,11,'Publications','San Francisco','Total','','11/11/2003','23/3/2011');
INSERT INTO MISSION (MISSION_ID, COLLAB_ID, NAME, PLACE, CLIENT, NOTES, START_DATE, END_DATE)
VALUES (23,6,'Site intranet','Toulouse','Air France','','3/5/2004','26/9/2011');
INSERT INTO MISSION (MISSION_ID, COLLAB_ID, NAME, PLACE, CLIENT, NOTES, START_DATE, END_DATE)
VALUES (24,24,'IHM de paramétrie','Boulogne','NavBoard','','1/1/2005','7/12/2010');
INSERT INTO MISSION (MISSION_ID, COLLAB_ID, NAME, PLACE, CLIENT, NOTES, START_DATE, END_DATE)
VALUES (25,14,'Application embarquée','New-York','Air France','','20/9/2002','11/2/2011');
COMMIT;
