---------------------------
--    DATA INSERTION     --
---------------------------

INSERT INTO AUTHENTICATION (AUTHENTICATION_ID, COLLEAGUE_ID, LOGIN, PASSWORD) VALUES (1,35,'v.dibi','c5e4db5cdd9eab069af1a40beb99ca10');
INSERT INTO AUTHENTICATION (AUTHENTICATION_ID, COLLEAGUE_ID, LOGIN, PASSWORD) VALUES (2,36,'j.marie-sainte','3e831076a4beb3543ce9822aef6b8d52');

COMMIT;

-----------------------
-- SEQUENCE UPDATE   --
-----------------------
DROP SEQUENCE SEQAUTH;
CREATE SEQUENCE SEQAUTH MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 3 NOCACHE;

COMMIT;