---------------------------
-- PRIMARY KEYS CREATION --
---------------------------
ALTER TABLE COLLABORATOR ADD CONSTRAINT COLLABORATORPK PRIMARY KEY (COLLAB_ID) USING INDEX TABLESPACE tmptestidx;

COMMIT;