---------------------------
--    DATA INSERTION     --
---------------------------
SET FOREIGN_KEY_CHECKS = 0;

Insert into CONCEPT (CONCEPT_ID,CATEGORY_ID,CONCEPT_NAME) values ('3','2','ORM');
Insert into CONCEPT (CONCEPT_ID,CATEGORY_ID,CONCEPT_NAME) values ('4','2','IOC');
Insert into CONCEPT (CONCEPT_ID,CATEGORY_ID,CONCEPT_NAME) values ('5','3','ORM');
Insert into CONCEPT (CONCEPT_ID,CATEGORY_ID,CONCEPT_NAME) values ('6','3','IOC');
Insert into CONCEPT (CONCEPT_ID,CATEGORY_ID,CONCEPT_NAME) values ('7','4','IOC');
Insert into CONCEPT (CONCEPT_ID,CATEGORY_ID,CONCEPT_NAME) values ('8','4','ORM');
Insert into CONCEPT (CONCEPT_ID,CATEGORY_ID,CONCEPT_NAME) values ('9','5','SGBD');
Insert into CONCEPT (CONCEPT_ID,CATEGORY_ID,CONCEPT_NAME) values ('11','2','TESTS UNITAIRES');
Insert into CONCEPT (CONCEPT_ID,CATEGORY_ID,CONCEPT_NAME) values ('12','6','CONCEPTION');
Insert into CONCEPT (CONCEPT_ID,CATEGORY_ID,CONCEPT_NAME) values ('13','7','QUALITÉ');
Insert into CONCEPT (CONCEPT_ID,CATEGORY_ID,CONCEPT_NAME) values ('14','8','SUIVI');
Insert into CONCEPT (CONCEPT_ID,CATEGORY_ID,CONCEPT_NAME) values ('15','8','GESTION');
Insert into CONCEPT (CONCEPT_ID,CATEGORY_ID,CONCEPT_NAME) values ('16','9','SUIVI');
Insert into CONCEPT (CONCEPT_ID,CATEGORY_ID,CONCEPT_NAME) values ('17','9','GESTION');
Insert into CONCEPT (CONCEPT_ID,CATEGORY_ID,CONCEPT_NAME) values ('39','27','CONCEPT DE TEST');
Insert into CONCEPT (CONCEPT_ID,CATEGORY_ID,CONCEPT_NAME) values ('1','1','IOC');
Insert into CONCEPT (CONCEPT_ID,CATEGORY_ID,CONCEPT_NAME) values ('2','1','ORM');

COMMIT;

SET FOREIGN_KEY_CHECKS = 1;

