---------------------------
--    DATA INSERTION     --
---------------------------
SET FOREIGN_KEY_CHECKS = 0;

Insert into CATEGORY (CATEGORY_ID,CATEGORY_NAME) values ('2','.NET');
Insert into CATEGORY (CATEGORY_ID,CATEGORY_NAME) values ('3','PHP');
Insert into CATEGORY (CATEGORY_ID,CATEGORY_NAME) values ('4','C#');
Insert into CATEGORY (CATEGORY_ID,CATEGORY_NAME) values ('5','SGBD');
Insert into CATEGORY (CATEGORY_ID,CATEGORY_NAME) values ('6','CONCEPTION');
Insert into CATEGORY (CATEGORY_ID,CATEGORY_NAME) values ('7','QUALITÉ');
Insert into CATEGORY (CATEGORY_ID,CATEGORY_NAME) values ('8','AMOA');
Insert into CATEGORY (CATEGORY_ID,CATEGORY_NAME) values ('9','PMO');
Insert into CATEGORY (CATEGORY_ID,CATEGORY_NAME) values ('26','CATEGORIE DE TEST');
Insert into CATEGORY (CATEGORY_ID,CATEGORY_NAME) values ('27','CATEGROEI DE TEST');
Insert into CATEGORY (CATEGORY_ID,CATEGORY_NAME) values ('1','JAVA EE');
Insert into CATEGORY (CATEGORY_ID,CATEGORY_NAME) values ('28','TEST CATEG');


COMMIT;

SET FOREIGN_KEY_CHECKS = 1;
