---------------------------
--    DATA INSERTION     --
---------------------------
SET FOREIGN_KEY_CHECKS = 0;
Insert into BUSINESS_ENGINEER (B_ENGINEER_ID,FIRST_NAME,LAST_NAME,BUSINESS_UNIT) values ('1','David','HAYEK','Banque/Finance');
Insert into BUSINESS_ENGINEER (B_ENGINEER_ID,FIRST_NAME,LAST_NAME,BUSINESS_UNIT) values ('2','Pierre-Yves','ETOURNEAU','Media');
Insert into BUSINESS_ENGINEER (B_ENGINEER_ID,FIRST_NAME,LAST_NAME,BUSINESS_UNIT) values ('3','Julie','VIGNERON','Industrie');
Insert into BUSINESS_ENGINEER (B_ENGINEER_ID,FIRST_NAME,LAST_NAME,BUSINESS_UNIT) values ('4','Déborah','ATTIAS','Tourisme');
Insert into BUSINESS_ENGINEER (B_ENGINEER_ID,FIRST_NAME,LAST_NAME,BUSINESS_UNIT) values ('5','Renaud','MIGNE','BI');
Insert into BUSINESS_ENGINEER (B_ENGINEER_ID,FIRST_NAME,LAST_NAME,BUSINESS_UNIT) values ('6','Colombe','TRAMOND','Services');

COMMIT;

SET FOREIGN_KEY_CHECKS = 1;
