---------------------------
--    DATA INSERTION     --
---------------------------
SET FOREIGN_KEY_CHECKS = 0;

Insert into TOOL (TOOL_ID,CONCEPT_ID,TOOL_NAME) values ('7','3','Castel Windsor');
Insert into TOOL (TOOL_ID,CONCEPT_ID,TOOL_NAME) values ('8','3','StructureMap');
Insert into TOOL (TOOL_ID,CONCEPT_ID,TOOL_NAME) values ('9','3','Spring.NET');
Insert into TOOL (TOOL_ID,CONCEPT_ID,TOOL_NAME) values ('10','3','Autofac');
Insert into TOOL (TOOL_ID,CONCEPT_ID,TOOL_NAME) values ('11','3','Unity');
Insert into TOOL (TOOL_ID,CONCEPT_ID,TOOL_NAME) values ('12','3','Puzzle.Nfactory');
Insert into TOOL (TOOL_ID,CONCEPT_ID,TOOL_NAME) values ('13','3','Ninject');
Insert into TOOL (TOOL_ID,CONCEPT_ID,TOOL_NAME) values ('14','3','S2Container.NET');
Insert into TOOL (TOOL_ID,CONCEPT_ID,TOOL_NAME) values ('15','3','PicoContainer.NET');
Insert into TOOL (TOOL_ID,CONCEPT_ID,TOOL_NAME) values ('16','3','LinFu');
Insert into TOOL (TOOL_ID,CONCEPT_ID,TOOL_NAME) values ('17','4','Microsoft ADO.NET');
Insert into TOOL (TOOL_ID,CONCEPT_ID,TOOL_NAME) values ('18','4','Microsoft Enterprise Library');
Insert into TOOL (TOOL_ID,CONCEPT_ID,TOOL_NAME) values ('19','4','CustomORM');
Insert into TOOL (TOOL_ID,CONCEPT_ID,TOOL_NAME) values ('20','5','Doctrine');
Insert into TOOL (TOOL_ID,CONCEPT_ID,TOOL_NAME) values ('21','5','Propel');
Insert into TOOL (TOOL_ID,CONCEPT_ID,TOOL_NAME) values ('22','5','PHPMyObject');
Insert into TOOL (TOOL_ID,CONCEPT_ID,TOOL_NAME) values ('23','5','JDAO ');
Insert into TOOL (TOOL_ID,CONCEPT_ID,TOOL_NAME) values ('24','6','Drip');
Insert into TOOL (TOOL_ID,CONCEPT_ID,TOOL_NAME) values ('25','6','Garden');
Insert into TOOL (TOOL_ID,CONCEPT_ID,TOOL_NAME) values ('26','6','Solar');
Insert into TOOL (TOOL_ID,CONCEPT_ID,TOOL_NAME) values ('27','6','Phemto');
Insert into TOOL (TOOL_ID,CONCEPT_ID,TOOL_NAME) values ('28','6','Seasar');
Insert into TOOL (TOOL_ID,CONCEPT_ID,TOOL_NAME) values ('29','6','ClawPHP');
Insert into TOOL (TOOL_ID,CONCEPT_ID,TOOL_NAME) values ('30','6','WACT');
Insert into TOOL (TOOL_ID,CONCEPT_ID,TOOL_NAME) values ('31','7','Windsor');
Insert into TOOL (TOOL_ID,CONCEPT_ID,TOOL_NAME) values ('32','8','Nhibernate');
Insert into TOOL (TOOL_ID,CONCEPT_ID,TOOL_NAME) values ('33','8','Subsoniq');
Insert into TOOL (TOOL_ID,CONCEPT_ID,TOOL_NAME) values ('34','8','Castle ActiveRecord');
Insert into TOOL (TOOL_ID,CONCEPT_ID,TOOL_NAME) values ('35','8','NH');
Insert into TOOL (TOOL_ID,CONCEPT_ID,TOOL_NAME) values ('36','8','EF');
Insert into TOOL (TOOL_ID,CONCEPT_ID,TOOL_NAME) values ('37','8','LLBLGenPro');
Insert into TOOL (TOOL_ID,CONCEPT_ID,TOOL_NAME) values ('38','9','SQL');
Insert into TOOL (TOOL_ID,CONCEPT_ID,TOOL_NAME) values ('39','9','DB2');
Insert into TOOL (TOOL_ID,CONCEPT_ID,TOOL_NAME) values ('40','9','IBM Informix ');
Insert into TOOL (TOOL_ID,CONCEPT_ID,TOOL_NAME) values ('41','9','IBM Cloudscape ');
Insert into TOOL (TOOL_ID,CONCEPT_ID,TOOL_NAME) values ('42','9','SQL Server');
Insert into TOOL (TOOL_ID,CONCEPT_ID,TOOL_NAME) values ('43','9','Access');
Insert into TOOL (TOOL_ID,CONCEPT_ID,TOOL_NAME) values ('44','9','Oracle');
Insert into TOOL (TOOL_ID,CONCEPT_ID,TOOL_NAME) values ('45','9','Hyperion EssBase');
Insert into TOOL (TOOL_ID,CONCEPT_ID,TOOL_NAME) values ('46','9','MySQL');
Insert into TOOL (TOOL_ID,CONCEPT_ID,TOOL_NAME) values ('47','9','Java DB');
Insert into TOOL (TOOL_ID,CONCEPT_ID,TOOL_NAME) values ('48','9','PostgreSQL');
Insert into TOOL (TOOL_ID,CONCEPT_ID,TOOL_NAME) values ('49','9','Sybase');
Insert into TOOL (TOOL_ID,CONCEPT_ID,TOOL_NAME) values ('50','9','SQLite');
Insert into TOOL (TOOL_ID,CONCEPT_ID,TOOL_NAME) values ('51','12','ALM');
Insert into TOOL (TOOL_ID,CONCEPT_ID,TOOL_NAME) values ('52','12','UML');
Insert into TOOL (TOOL_ID,CONCEPT_ID,TOOL_NAME) values ('53','12','Merise');
Insert into TOOL (TOOL_ID,CONCEPT_ID,TOOL_NAME) values ('55','11','Nunit');
Insert into TOOL (TOOL_ID,CONCEPT_ID,TOOL_NAME) values ('56','13','Sonar');
Insert into TOOL (TOOL_ID,CONCEPT_ID,TOOL_NAME) values ('57','14','Word');
Insert into TOOL (TOOL_ID,CONCEPT_ID,TOOL_NAME) values ('58','14','Excel');
Insert into TOOL (TOOL_ID,CONCEPT_ID,TOOL_NAME) values ('59','15','Icalendar');
Insert into TOOL (TOOL_ID,CONCEPT_ID,TOOL_NAME) values ('60','15','Evernote');
Insert into TOOL (TOOL_ID,CONCEPT_ID,TOOL_NAME) values ('61','16','Notepad++');
Insert into TOOL (TOOL_ID,CONCEPT_ID,TOOL_NAME) values ('62','16','BlocNote');
Insert into TOOL (TOOL_ID,CONCEPT_ID,TOOL_NAME) values ('63','17','Agenda Lite');
Insert into TOOL (TOOL_ID,CONCEPT_ID,TOOL_NAME) values ('64','17','LockCalendar ');
Insert into TOOL (TOOL_ID,CONCEPT_ID,TOOL_NAME) values ('70','13','add_tool_test3');
Insert into TOOL (TOOL_ID,CONCEPT_ID,TOOL_NAME) values ('73','9','add_tool_SGBD');
Insert into TOOL (TOOL_ID,CONCEPT_ID,TOOL_NAME) values ('68','13','add_tool_test');
Insert into TOOL (TOOL_ID,CONCEPT_ID,TOOL_NAME) values ('69','13','add_tool_test2');
Insert into TOOL (TOOL_ID,CONCEPT_ID,TOOL_NAME) values ('74','13','testtesttest');
Insert into TOOL (TOOL_ID,CONCEPT_ID,TOOL_NAME) values ('75','13','test_add_tool_again');
Insert into TOOL (TOOL_ID,CONCEPT_ID,TOOL_NAME) values ('76','13','testdetest');
Insert into TOOL (TOOL_ID,CONCEPT_ID,TOOL_NAME) values ('71','13','add_tool_test');
Insert into TOOL (TOOL_ID,CONCEPT_ID,TOOL_NAME) values ('72','13','add_tool_test');
Insert into TOOL (TOOL_ID,CONCEPT_ID,TOOL_NAME) values ('5','2','MyBATIS');
Insert into TOOL (TOOL_ID,CONCEPT_ID,TOOL_NAME) values ('6','2','jOOQ');
Insert into TOOL (TOOL_ID,CONCEPT_ID,TOOL_NAME) values ('1','1','Google Guice');
Insert into TOOL (TOOL_ID,CONCEPT_ID,TOOL_NAME) values ('2','1','PicoContainer');
Insert into TOOL (TOOL_ID,CONCEPT_ID,TOOL_NAME) values ('3','1','Spring');
Insert into TOOL (TOOL_ID,CONCEPT_ID,TOOL_NAME) values ('4','2','Hibernate');

COMMIT;

SET FOREIGN_KEY_CHECKS = 1;
