---------------------------
--    DATA INSERTION     --
---------------------------
SET FOREIGN_KEY_CHECKS = 0;

Insert into OBJECTIVE_SCORE (OBJECTIVE_SCORE_ID,OBJECTIVE_SCORE_LABEL) values ('1','NOT ACHIEVED');
Insert into OBJECTIVE_SCORE (OBJECTIVE_SCORE_ID,OBJECTIVE_SCORE_LABEL) values ('2','PARTLY ACHIEVED');
Insert into OBJECTIVE_SCORE (OBJECTIVE_SCORE_ID,OBJECTIVE_SCORE_LABEL) values ('3','ACHIEVED');
Insert into OBJECTIVE_SCORE (OBJECTIVE_SCORE_ID,OBJECTIVE_SCORE_LABEL) values ('4','ESCEEDED');

COMMIT;

SET FOREIGN_KEY_CHECKS = 1;
