----------------------------------------------------------------------
-- TABLE DE LIAISON DES MANAGER DES COLLABORATEURS ET DES OBJECTIFS --
----------------------------------------------------------------------

---------------------------
-- FOREIGN KEYS CREATION --
---------------------------
ALTER TABLE COLLAB_MANAGER_OBJ ADD CONSTRAINT COLLAB_MANAGER_OBJFK1 FOREIGN KEY (COLLAB_ID) REFERENCES COLLABORATOR (COLLAB_ID);
ALTER TABLE COLLAB_MANAGER_OBJ ADD CONSTRAINT COLLAB_MANAGER_OBJFK2 FOREIGN KEY (CMANAGER_ID) REFERENCES CMANAGER (CMANAGER_ID);
ALTER TABLE COLLAB_MANAGER_OBJ ADD CONSTRAINT COLLAB_MANAGER_OBJFK3 FOREIGN KEY (OBJECTIVE_ID) REFERENCES OBJECTIVE (OBJECTIVE_ID);