
---------------------------
-- PRIMARY KEYS CREATION --
---------------------------
ALTER TABLE CONCEPT ADD CONSTRAINT CONCEPTPK PRIMARY KEY (CONCEPT_ID) USING INDEX TABLESPACE TMP00IDX1;

---------------------------
-- FOREIGN KEYS CREATION --
---------------------------
ALTER TABLE CONCEPT ADD CONSTRAINT CONCEPTFK PRIMARY KEY (CATEGORY_ID) REFERENCES CATEGORY (CATEGORY_ID);

