---------------------------
-- FOREIGN KEYS CREATION --
---------------------------
ALTER TABLE COLLEAGUE ADD CONSTRAINT COLLEAGUEFK1 FOREIGN KEY (PROFILE_ID) REFERENCES PROFILE (PROFILE_ID);
ALTER TABLE COLLEAGUE ADD CONSTRAINT COLLEAGUEFK2 FOREIGN KEY (MANAGER_ID) REFERENCES MANAGER (MANAGER_ID);

COMMIT;