---------------------------
-- FOREIGN KEYS CREATION --
---------------------------
ALTER TABLE USER_ROLE ADD CONSTRAINT USER_ROLEFK1 FOREIGN KEY (AUTHENTICATION_ID) REFERENCES AUTHENTICATION (AUTHENTICATION_ID);

COMMIT;