---------------------------
-- FOREIGN KEYS CREATION --
---------------------------
ALTER TABLE COLLEAGUE_MANAGER_OBJ ADD CONSTRAINT COLLEAGUE_MANAGER_OBJFK1 FOREIGN KEY (COLLEAGUE_ID) REFERENCES COLLEAGUE (COLLEAGUE_ID) ON DELETE CASCADE;
ALTER TABLE COLLEAGUE_MANAGER_OBJ ADD CONSTRAINT COLLEAGUE_MANAGER_OBJFK3 FOREIGN KEY (OBJECTIVE_ID) REFERENCES OBJECTIVE (OBJECTIVE_ID);

COMMIT;