---------------------------
-- FOREIGN KEYS CREATION --
---------------------------
ALTER TABLE MANAGER ADD CONSTRAINT MANAGERFK1 FOREIGN KEY (PROFILE_ID) REFERENCES PROFILE (PROFILE_ID);
ALTER TABLE MANAGER ADD CONSTRAINT MANAGERFK2 FOREIGN KEY (B_ENGINEER_ID) REFERENCES BUSINESS_ENGINEER (B_ENGINEER_ID);

COMMIT;

