---------------------------
-- FOREIGN KEYS CREATION --
---------------------------
ALTER TABLE CONCEPT ADD CONSTRAINT CONCEPTFK PRIMARY KEY (CATEGORY_ID) REFERENCES CATEGORY (CATEGORY_ID);

COMMIT;

