---------------------------
-- FOREIGN KEYS CREATION --
---------------------------
ALTER TABLE MISSION ADD CONSTRAINT MISSIONFK FOREIGN KEY (COLLAB_ID) REFERENCES COLLABORATOR (COLLAB_ID);

COMMIT;
