---------------------------
-- FOREIGN KEYS CREATION --
---------------------------
ALTER TABLE MISSION ADD CONSTRAINT MISSIONFK FOREIGN KEY (COLLEAGUE_ID) REFERENCES COLLEAGUE (COLLEAGUE_ID) ON DELETE CASCADE;

COMMIT;
