---------------------------
-- FOREIGN KEYS CREATION --
---------------------------
ALTER TABLE MANAGER ADD CONSTRAINT MANAGERFK1 PRIMARY KEY (PROFILE_ID) REFERENCES PROFILE (PROFILE_ID);

COMMIT;

