---------------------------
-- FOREIGN KEYS CREATION --
---------------------------
ALTER TABLE COLLABORATOR ADD CONSTRAINT COLLABORATORFK1 FOREIGN KEY (PROFILE_ID) REFERENCES PROFILETYPE (PROFILE_ID);
ALTER TABLE COLLABORATOR ADD CONSTRAINT COLLABORATORFK2 FOREIGN KEY (MANAGER_ID) REFERENCES CMANAGER (MANAGER_ID);

COMMIT;