---------------------------
-- FOREIGN KEYS CREATION --
---------------------------
ALTER TABLE AUTHENTICATION ADD CONSTRAINT AUTHENTICATIONFK1 FOREIGN KEY (COLLEAGUE_ID) REFERENCES COLLABORATOR (COLLAB_ID);
ALTER TABLE AUTHENTICATION ADD CONSTRAINT AUTHENTICATIONFK2 FOREIGN KEY (ROLE_ID) REFERENCES USER_ROLE (ROLE_ID);

COMMIT;