---------------------------
-- FOREIGN KEYS CREATION --
---------------------------

ALTER TABLE NOTIFICATION ADD CONSTRAINT NOTIFICATION_FK FOREIGN KEY (COLLEAGUE_ID) REFERENCES COLLEAGUE (COLLEAGUE_ID) ON DELETE CASCADE ENABLE;

COMMIT;