---------------------------
-- FOREIGN KEYS CREATION --
---------------------------
ALTER TABLE COLLEAGUE ADD CONSTRAINT COLLEAGUEFK1 FOREIGN KEY (PROFILE_ID) REFERENCES PROFILE (PROFILE_ID);
ALTER TABLE COLLEAGUE ADD CONSTRAINT COLLEAGUEFK3 FOREIGN KEY (B_ENGINEER_ID) REFERENCES BUSINESS_ENGINEER (B_ENGINEER_ID);

COMMIT;