---------------------------
-- FOREIGN KEYS CREATION --
---------------------------
ALTER TABLE COLLABORATOR ADD CONSTRAINT COLLABORATORFK1 FOREIGN KEY (PROFILE_ID) REFERENCES PROFILE (PROFILE_ID);
ALTER TABLE COLLABORATOR ADD CONSTRAINT COLLABORATORFK2 FOREIGN KEY (MANAGER_ID) REFERENCES MANAGER (MANAGER_ID);
ALTER TABLE COLLABORATOR ADD CONSTRAINT COLLABORATORFK3 FOREIGN KEY (B_ENGINEER_ID) REFERENCES BUSINESS_ENGINEER (B_ENGINEER_ID);

COMMIT;