---------------------------
-- FOREIGN KEYS CREATION --
---------------------------
ALTER TABLE AUTHENTIFICATION ADD CONSTRAINT AUTHENTIFICATIONFK1 FOREIGN KEY (COLLAB_ID) REFERENCES COLLABORATOR (COLLAB_ID);

COMMIT;