---------------------------
-- FOREIGN KEYS CREATION --
---------------------------

ALTER TABLE NOTIFICATION_OPTION ADD CONSTRAINT NOTIFICATION_OPTIONFK1 FOREIGN KEY (COLLEAGUE_ID) REFERENCES COLLEAGUE (COLLEAGUE_ID) ON DELETE CASCADE ENABLE;
ALTER TABLE NOTIFICATION_OPTION ADD CONSTRAINT NOTIFICATION_OPTIONFK2 FOREIGN KEY (FREQUENCY_ID) REFERENCES FREQUENCY (FREQUENCY_ID) ENABLE;

COMMIT;