------------------------
-- CREATION DES INDEX --
------------------------

DROP INDEX COLLEAGUEIDX ON COLLEAGUE;
CREATE INDEX COLLEAGUEIDX1 ON COLLEAGUE (COLLEAGUE_ID);

DROP INDEX CATEGORYIDX ON CATEGORY;
CREATE INDEX CATEGORYIDX ON CATEGORY (CATEGORY_ID);

DROP INDEX CONCEPTIDX1 ON CONCEPT;
CREATE INDEX CONCEPTIDX1 ON CONCEPT (CONCEPT_ID);

DROP INDEX CONCEPTIDX2 ON CONCEPT;
CREATE INDEX CONCEPTIDX2 ON CONCEPT (CATEG_ID);

DROP INDEX TOOLIDX1 ON TOOL;
CREATE INDEX TOOLIDX1 ON TOOL (TOOL_ID);

DROP INDEX TOOLIDX2 ON TOOL;;
CREATE INDEX TOOLIDX2 ON TOOL (CONCEPT_ID);

DROP INDEX SCOREIDX1 ON SCORE;
CREATE INDEX SCOREIDX1 ON SCORE (COLLEAGUE_ID);

DROP INDEX SCOREIDX2 ON SCORE;
CREATE INDEX SCOREIDX2 ON SCORE (TOOL_ID);

DROP INDEX OBJECTIVEIDX ON OBJECTIVE;
CREATE INDEX OBJECTIVEIDX ON OBJECTIVE (OBJECTIVE_ID);

DROP INDEX MISSIONIDX1 ON MISSION;
CREATE INDEX MISSIONIDX ON MISSION (MISSION_ID);

DROP INDEX MISSIONIDX2 ON MISSION;
CREATE INDEX MISSIONIDX2 ON MISSION (COLLEAGUE_ID);

DROP INDEX CLIENTIDX1 ON CLIENT;
CREATE INDEX CLIENTIDX1 ON CLIENT (CLIENT_ID);