------------------------
-- CREATION DES INDEX --
------------------------
SET FOREIGN_KEY_CHECKS = 0;

DROP INDEX COLLEAGUE1 ON COLLEAGUE;
CREATE UNIQUE INDEX COLLEAGUE1 ON COLLEAGUE (COLLEAGUE_ID); 

DROP INDEX TASKPK ON TASK;
CREATE UNIQUE INDEX TASKPK ON TASK (TASK_ID); 

DROP INDEX BUSINESS_ENGINEERPK ON BUSINESS_ENGINEER;
CREATE UNIQUE INDEX BUSINESS_ENGINEERPK ON BUSINESS_ENGINEER (B_ENGINEER_ID);

DROP INDEX USER_ROLEPK ON USER_ROLE;
CREATE UNIQUE INDEX USER_ROLEPK ON USER_ROLE (ROLE_ID);

DROP INDEX OBJECTIVEPK ON OBJECTIVE;
CREATE UNIQUE INDEX OBJECTIVEPK ON OBJECTIVE (OBJECTIVE_ID);

DROP INDEX TOOLPK ON TOOL;
CREATE UNIQUE INDEX TOOLPK ON TOOL (TOOL_ID);

DROP INDEX CATEGORYPK ON CATEGORY;
CREATE UNIQUE INDEX CATEGORYPK ON CATEGORY (CATEGORY_ID);

DROP INDEX MISSION_TOOLPK ON MISSION_TOOL;
CREATE UNIQUE INDEX MISSION_TOOLPK ON MISSION_TOOL (MISSION_ID, TOOL_ID);

DROP INDEX CLIENTPK ON CLIENT;
CREATE UNIQUE INDEX CLIENTPK ON CLIENT (CLIENT_ID);

DROP INDEX PARAMETER_PK ON PARAMETER;
CREATE UNIQUE INDEX PARAMETER_PK ON PARAMETER (ID);

DROP INDEX MISSIONPK ON MISSION;
CREATE UNIQUE INDEX MISSIONPK ON MISSION (MISSION_ID);

DROP INDEX CONCEPTPK ON CONCEPT;
CREATE UNIQUE INDEX CONCEPTPK ON CONCEPT (CONCEPT_ID);

DROP INDEX MANAGERPK ON MANAGER;
CREATE UNIQUE INDEX MANAGERPK ON MANAGER (MANAGER_ID);

DROP INDEX AUTHENTICATIONPK ON AUTHENTICATION;
CREATE UNIQUE INDEX AUTHENTICATIONPK ON AUTHENTICATION (AUTHENTICATION_ID);

DROP INDEX PROFILEPK ON PROFILE;
CREATE UNIQUE INDEX PROFILEPK ON PROFILE (PROFILE_ID);


SET FOREIGN_KEY_CHECKS = 1;