
--------------------
-- TABLE CREATION --
--------------------
DROP TABLE CONCEPT CASCADE CONSTRAINTS;
CREATE TABLE CONCEPT
(
	CONCEPT_ID    VARCHAR2(10) NOT NULL,
	CATEGORY_ID   VARCHAR2(10) NOT NULL,
	CONCEPT_NAME  VARCHAR2(20) NOT NULL
)
TABLESPACE tmp00dta;

COMMENT ON TABLE CONCEPT IS 'Tables des concepts';

-----------------------
-- SEQUENCE CREATION --
-----------------------
CREATE SEQUENCE SEQCONCEPT MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 1 NOCACHE;

---------------------------
-- PRIMARY KEYS CREATION --
---------------------------
ALTER TABLE CONCEPT ADD CONSTRAINT CONCEPTPK PRIMARY KEY (CONCEPT_ID) USING INDEX TABLESPACE TMP00IDX1;

---------------------------
-- FOREIGN KEYS CREATION --
---------------------------
ALTER TABLE CONCEPT ADD CONSTRAINT CONCEPTFK PRIMARY KEY (CATEGORY_ID) REFERENCES CATEGORY (CATEGORY_ID);

