-----------------------
-- TABLE DES ACTIONS --
-----------------------

--------------------
-- TABLE CREATION --
--------------------
DROP TABLE ACTIONS CASCADE CONSTRAINTS;
CREATE TABLE ACTIONS
(
	ACTION_ID     VARCHAR2(10) NOT NULL,
	ACTION_NAME   VARCHAR2(10) NOT NULL,
	ACTION_TYPE   VARCHAR2(10) NOT NULL,
	STATUS        NUMBER(1),
	TARGET_DATE   DATE,
	PRIORITY      NUMBER(1),
	EFFORT        NUMBER(1)
)
TABLESPACE tmp00dta;

COMMENT ON TABLE ACTIONS IS 'Tables des actions';

-----------------------
-- SEQUENCE CREATION --
-----------------------
CREATE SEQUENCE SEQACTIONS MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 1 NOCACHE;

---------------------------
-- PRIMARY KEYS CREATION --
---------------------------
ALTER TABLE ACTIONS ADD CONSTRAINT ACTIONSPK PRIMARY KEY (ACTION_ID) USING INDEX TABLESPACE TMP00IDX1;
