-------------------
-- TABLE DES CMs --
-------------------

--------------------
-- TABLE CREATION --
--------------------
DROP TABLE CMANAGER CASCADE CONSTRAINTS;
CREATE TABLE CMANAGER
(
	CMANAGER_ID       VARCHAR2(10) NOT NULL,
	TYP_PROFIL_ID     VARCHAR2(10) NOT NULL,
	LAST_NAME         VARCHAR2(20),
	FIRST_NAME        VARCHAR2(20),
	EMAIL             VARCHAR2(30),
	PHONE_NUM         NUMBER(10),
	EMPLOYMENT_DATE   DATE,
	EXPERIENCE        NUMBER(2),
	BUSINESS_ENGINEER VARCHAR2(40)
)
TABLESPACE tmp00dta;

COMMENT ON TABLE CMANAGER IS 'Tables des CMs';

-----------------------
-- SEQUENCE CREATION --
-----------------------
CREATE SEQUENCE SEQCMANAG MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 1 NOCACHE;

---------------------------
-- PRIMARY KEYS CREATION --
---------------------------
ALTER TABLE CMANAGER ADD CONSTRAINT CMANAGERPK PRIMARY KEY (CMANAGER_ID) USING INDEX TABLESPACE TMP00IDX1;

---------------------------
-- FOREIGN KEYS CREATION --
---------------------------
ALTER TABLE CMANAGER ADD CONSTRAINT CMANAGERFK1 PRIMARY KEY (TYP_PROFIL_ID) REFERENCES PROFILETYPE (TYP_PROFIL_ID);
