----------------------
-- TABLE DES NOTES  --
----------------------


--------------------
-- TABLE CREATION --
--------------------
DROP TABLE SCORE CASCADE CONSTRAINTS;
CREATE TABLE SCORE
(
	COLLAB_ID   VARCHAR2(10) NOT NULL,
	TOOLS_ID    VARCHAR2(10) NOT NULL,
	SCORE       NUMBER(1)
)
TABLESPACE tmp00dta;

COMMENT ON TABLE SCORE IS 'Tables des notes';

-----------------------
-- SEQUENCE CREATION --
-----------------------
CREATE SEQUENCE SEQSCORE MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 1 NOCACHE;

---------------------------
-- FOREIGN KEYS CREATION --
---------------------------
ALTER TABLE SCORE ADD CONSTRAINT SCOREFK1 FOREIGN KEY (COLLAB_ID) REFERENCES COLLABORATOR (COLLAB_ID);
ALTER TABLE SCORE ADD CONSTRAINT SCOREFK2 FOREIGN KEY (TOOLS_ID)  REFERENCES TOOLS (COLLAB_ID);

