-----------------------
-- TABLE DES OUTILS  --
-----------------------

--------------------
-- TABLE CREATION --
--------------------
DROP TABLE TOOL CASCADE CONSTRAINTS;
CREATE TABLE TOOL
(
	TOOL_ID        VARCHAR2(10) NOT NULL,
	CONCEPT_ID     VARCHAR2(10) NOT NULL,
	TOOLS_NAME     VARCHAR2(20) NOT NULL,
	USE_FREQUENCY  NUMBER(1)NOT NULL,
	NOT_USE_TIME   NUMBER(1) NOT NULL
)
TABLESPACE tmp00dta;

COMMENT ON TABLE TOOLS IS 'Table des outils';

-----------------------
-- SEQUENCE CREATION --
-----------------------
CREATE SEQUENCE SEQTOOL MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 1 NOCACHE;

---------------------------
-- PRIMARY KEYS CREATION --
---------------------------
ALTER TABLE TOOL ADD CONSTRAINT TOOLPK PRIMARY KEY (TOOL_ID) USING INDEX TABLESPACE TMP00IDX1;

---------------------------
-- FOREIGN KEYS CREATION --
---------------------------
ALTER TABLE SCORE ADD CONSTRAINT TOOLFK1 FOREIGN KEY (CONCEPT_ID) REFERENCES CONCEPT (CONCEPT_ID);
