-------------------------
-- TABLE DES MISSIONS  --
-------------------------


--------------------
-- TABLE CREATION --
--------------------
DROP TABLE MISSION CASCADE CONSTRAINTS;
CREATE TABLE MISSION
(
	MISSION_ID VARCHAR2(10) NOT NULL,
	COLLAB_ID VARCHAR2(10) NOT NULL,
	CLIENT VARCHAR2(10) NOT NULL,
	START_DATE DATE NOT NULL,
	END_DATE DATE
)
TABLESPACE tmp00dta;

COMMENT ON TABLE MISSION IS 'Tables des missions';

-----------------------
-- SEQUENCE CREATION --
-----------------------
CREATE SEQUENCE SEQMISSION MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 1 NOCACHE;

---------------------------
-- PRIMARY KEYS CREATION --
---------------------------
ALTER TABLE MISSION ADD CONSTRAINT MISSIONPK PRIMARY KEY (MISSION_ID) USING INDEX TABLESPACE TMP00IDX1;

---------------------------
-- FOREIGN KEYS CREATION --
---------------------------
ALTER TABLE SCORE ADD CONSTRAINT MISSIONFK1 FOREIGN KEY (COLLAB_ID) REFERENCES COLLABORATOR (COLLAB_ID);
