----------------------------------------
-- TABLE DE LIEN OBJECTIFS ET ACTIONS --
----------------------------------------


--------------------
-- TABLE CREATION --
--------------------
DROP TABLE OBJACTIONS CASCADE CONSTRAINTS;
CREATE TABLE OBJACTIONS
(
	OBJ_EA_ID   VARCHAR2(10) NOT NULL,
	ACTION_ID   VARCHAR2(10) NOT NULL
)
TABLESPACE tmp00dta;

COMMENT ON TABLE OBJACTIONS IS 'Tables des objectifs et actions';

-----------------------
-- SEQUENCE CREATION --
-----------------------
CREATE SEQUENCE SEQOBJACTIONS MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 1 NOCACHE;

---------------------------
-- FOREIGN KEYS CREATION --
---------------------------
ALTER TABLE OBJACTIONS ADD CONSTRAINT OBJACTIONSFK1 FOREIGN KEY (OBJ_EA_ID) REFERENCES EAOBJECTIVE (OBJ_EA_ID);
ALTER TABLE OBJACTIONS ADD CONSTRAINT OBJACTIONSFK2 FOREIGN KEY (ACTION_ID) REFERENCES ACTIONS (ACTION_ID);

