------------------------------
-- TABLE DES COLLABORATEURS --
------------------------------

--------------------
-- TABLE CREATION --
--------------------
DROP TABLE COLLABORATOR CASCADE CONSTRAINTS;
CREATE TABLE COLLABORATOR
(
	COLLAB_ID         VARCHAR2(10) NOT NULL,
	CMANAGER_ID       VARCHAR2(10) NOT NULL,     
	TYPE_PROFIL_ID    VARCHAR2(10) NOT NULL,
	CM_COLLAB_ID      VARCHAR2(10) NOT NULL,
	LAST_NAME         VARCHAR2(20) NOT NULL,
	FIRST_NAME        VARCHAR2(20) NOT NULL,
	EMAIL             VARCHAR2(30) NOT NULL,
	PHONE_NUM         NUMBER(10),
	EMPLOYMENT_DATE   DATE         NOT NULL,
	EXPERIENCE        NUMBER(2)   NOT NULL,
	BUSINESS_ENGINEER VARCHAR2(40)
)
TABLESPACE tmp00dta;

COMMENT ON TABLE COLLABORATOR IS 'Tables des collaborateurs';

-----------------------
-- SEQUENCE CREATION --
-----------------------
CREATE SEQUENCE SEQCOLLAB MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 1 NOCACHE;

DROP INDEX COLLABORATORIDX1;
CREATE INDEX COLLABORATORIDX1 ON COLLABORATOR (COD_EXCEL) TABLESPACE tmp00idx;

---------------------------
-- PRIMARY KEYS CREATION --
---------------------------
ALTER TABLE COLLABORATOR ADD CONSTRAINT COLLABORATOR1 PRIMARY KEY (COLLAB_ID) USING INDEX TABLESPACE tmp00idx;

---------------------------
-- FOREIGN KEYS CREATION --
---------------------------
ALTER TABLE COLLABORATOR ADD CONSTRAINT COLLABORATORFK1 FOREIGN KEY (TYPE_PROFIL_ID) REFERENCES PROFILETYPE (TYPE_PROFIL_ID);
ALTER TABLE COLLABORATOR ADD CONSTRAINT COLLABORATORFK2 FOREIGN KEY (CMANAGER_ID) REFERENCES CMANAGER (CMANAGER_ID);
